

temp$actor <- str_to_title(temp$actor)

unique(temp$actor)
###

temp$package[temp$package == 50] <- 5

temp$actor[temp$actor=="??"] <- 'Xxx'
temp$actor[temp$actor=="?"] <- 'Xxx'
temp$actor[startsWith(temp$actor, "X")] <- "All"


temp$actor[temp$actor=="Cut"] <- 'Break'

## correcting naming mistakes
temp$actor[temp$actor=="Us"] <- 'USA'
temp$actor[temp$actor=="US"] <- 'USA'
temp$actor[temp$actor=="Usa"] <- 'USA'
temp$actor[temp$actor=="Uusa"] <- 'USA'


temp$actor[temp$actor=="United States"] <- 'USA'
temp$actor[temp$actor=="United States Of America"] <- 'USA'
temp$actor[temp$actor=="United Kingdom Of Great Britain And Northern Ireland"] <- 'UK'
#temp$actor[temp$actor=="Uk"] <- 'United Kingdom'
temp$actor[temp$actor=="United Kingdom"] <- 'UK'
temp$actor[temp$actor=="Uk"] <- 'UK'
temp$actor[temp$actor=="Uf"] <- 'UK'

temp$actor[temp$actor=="Russian Federation"] <- 'Russia'
temp$actor[temp$actor=="Russian Fed"] <- 'Russia'
temp$actor[temp$actor=="Russsia"] <- 'Russia'
temp$actor[temp$actor=="Rusiia"] <- 'Russia'
temp$actor[temp$actor=="Alegeria"] <- 'Algeria'
temp$actor[temp$actor=="Alergia"] <- 'Algeria'
temp$actor[temp$actor=="Alregia"] <- 'Algeria'
temp$actor[temp$actor=="African Union"] <- 'Algeria'
temp$actor[temp$actor=="Africain Group"] <- 'Algeria'
temp$actor[temp$actor=="Aus"] <- 'Australia'
temp$actor[temp$actor=="Ausralia"] <- 'Australia'
temp$actor[temp$actor=="Autstralia"] <- 'Australia'
temp$actor[temp$actor=="Australai"] <- 'Australia'
temp$actor[temp$actor=="Austrlia"] <- 'Australia'
temp$actor[temp$actor=="Austrlia"] <- 'Australia'
temp$actor[temp$actor=="Austtralia"] <- 'Australia'
temp$actor[temp$actor=="Autralia"] <- 'Australia'
temp$actor[temp$actor=="Austalia"] <- 'Australia'
temp$actor[temp$actor=="Austraia"] <- 'Australia'
temp$actor[temp$actor=="Australie"] <- 'Australia'
temp$actor[temp$actor=="Austrlaia"] <- 'Australia'
temp$actor[temp$actor=="Suatralia"] <- 'Australia'

temp$actor[temp$actor=="Argentna"] <- 'Argentina'
temp$actor[temp$actor=="Aregntina"] <- 'Argentina'
temp$actor[temp$actor=="Arentina"] <- 'Argentina'
temp$actor[temp$actor=="Agrentina"] <- 'Argentina'
temp$actor[temp$actor=="Aregentina"] <- 'Argentina'
temp$actor[temp$actor=="Argenitna"] <- 'Argentina'
temp$actor[temp$actor=="Argetnina"] <- 'Argentina'
temp$actor[temp$actor=="Argentina Obo Clam"] <- 'Argentina'


temp$actor[temp$actor=="Antigua"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Antiua And Barbados"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Antigua And Barbados"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Antiugua And Barbuda"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Anitgua And Barbuda"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Antigua And Bermuda"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Atigua And Barbuda"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Antigua Andbarbuda"] <- 'Antigua And Barbuda'



temp$actor[temp$actor=="Azustralia"] <- 'Australia'
temp$actor[temp$actor=="Australlia"] <- 'Australia'
temp$actor[temp$actor=="Medhi Remaon"] <- 'Algeria'
temp$actor[temp$actor=="Argentinia"] <- 'Argentina'
temp$actor[temp$actor=="Barabados"] <- 'Barbados'
temp$actor[temp$actor=="Barbedos"] <- 'Barbados'
temp$actor[temp$actor=="Badbados"] <- 'Barbados'
temp$actor[temp$actor=="Babados"] <- 'Barbados'
temp$actor[temp$actor=="Barbaods"] <- 'Barbados'
temp$actor[temp$actor=="Barbardos"] <- 'Barbados'
temp$actor[temp$actor=="Barabdos"] <- 'Barbados'
temp$actor[temp$actor=="Barbads"] <- 'Barbados'
temp$actor[temp$actor=="Bardador"] <- 'Barbados'
temp$actor[temp$actor=="Basbados"] <- 'Barbados'
temp$actor[temp$actor=="Brabados"] <- 'Barbados'
temp$actor[temp$actor=="Barbados Obo Caricom"] <- 'Barbados'

temp$actor[temp$actor=="Caricom (Kahlil)"] <- 'Barbados'
temp$actor[temp$actor=="Caricom Kahlil"] <- 'Barbados'

temp$actor[temp$actor=="Baha,Mas"] <- 'Bahamas'
temp$actor[temp$actor=="Bahaman"] <- 'Bahamas'


temp$actor[temp$actor=="Boivia"] <- 'Bolivia'

temp$actor[temp$actor=="Burkino Faso"] <- 'Burkina Faso'

temp$actor[temp$actor=="Bangladesch"] <- 'Bangladesh'
temp$actor[temp$actor=="Bangaldesh"] <- 'Bangladesh'
temp$actor[temp$actor=="Bangldesh"] <- 'Bangladesh'
temp$actor[temp$actor=="Brasil"] <- 'Brazil'
temp$actor[temp$actor=="Vrazil"] <- 'Brazil'
temp$actor[temp$actor=="Barazil"] <- 'Brazil'
temp$actor[temp$actor=="Berlgium"] <- 'Belgium'
temp$actor[temp$actor=="Belgien"] <- 'Belgium'
temp$actor[temp$actor=="Belice"] <- 'Belize'
temp$actor[temp$actor=="Belize Obo Caricom"] <- 'Belize'

temp$actor[temp$actor=="Camroon"] <- 'Cameroon'
temp$actor[temp$actor=="Camerron"] <- 'Cameroon'
temp$actor[temp$actor=="Caeroon"] <- 'Cameroon'
temp$actor[temp$actor=="Camaeroon"] <- 'Cameroon'
temp$actor[temp$actor=="Camerroon"] <- 'Cameroon'


temp$actor[temp$actor=="Camaera On Iran"] <- 'Cameroon'

temp$actor[temp$actor=="Dom Rep"] <- 'Dominican Republic'



temp$actor[temp$actor=="Cabada"] <- 'Canada'
temp$actor[temp$actor=="Cnaada"] <- 'Canada'
temp$actor[temp$actor=="Canada Coming Back"] <- 'Canada'
temp$actor[temp$actor=="Canda"] <- 'Canada'
temp$actor[temp$actor=="Cananda"] <- 'Canada'
temp$actor[temp$actor=="Cnada"] <- 'Canada'
temp$actor[temp$actor=="Cadand"] <- 'Canada'
temp$actor[temp$actor=="Canaad"] <- 'Canada'

temp$actor[temp$actor=="Cr"] <- 'Costa Rica'

temp$actor[temp$actor=="Chair-Nulifer Oral"] <- 'Chair'
temp$actor[temp$actor=="Cil"] <- 'Chair'

temp$actor[temp$actor=="Clam/ Guatemala"] <- 'Clam'

temp$actor[temp$actor=="Credentals Commitee Ireland"] <- 'Credentals Commitee'



temp$actor[temp$actor=="Cape Verde"] <- 'Cabo Verde'
temp$actor[temp$actor=="Columbia"] <- 'Colombia'
temp$actor[temp$actor=="Colimbia"] <- 'Colombia'
temp$actor[temp$actor=="Colobia"] <- 'Colombia'
temp$actor[temp$actor=="Chin"] <- 'China'
temp$actor[temp$actor=="Chiane"] <- 'China'
temp$actor[temp$actor=="Chine"] <- 'China'
temp$actor[temp$actor=="Chiana"] <- 'China'

temp$actor[temp$actor=="Cote D`Ivoire"] <- 'Cote dIvoire'
temp$actor[temp$actor=="Cote Divoire"] <- 'Cote dIvoire'
temp$actor[temp$actor=="Cote dIvoire"] <- 'Cote dIvoire'
temp$actor[temp$actor=="Cote Divoire"] <- 'Cote dIvoire'
temp$actor[temp$actor=="C?te D'ivoire"] <- 'Cote dIvoire'
temp$actor[temp$actor=="Cote D Ivoire"] <- 'Cote dIvoire'
temp$actor[temp$actor=="Cote D Ivore"] <- 'Cote dIvoire'

temp$actor[temp$actor=="Congo, Democratic Republic Of"] <- 'Democratic Republic of the Congo'
temp$actor[temp$actor=="Cuba?"] <- "Cuba" 
temp$actor[temp$actor=="Eitrea"] <- 'Eritrea'
temp$actor[temp$actor=="Erritrea"] <- 'Eritrea'
temp$actor[temp$actor=="European Union"] <- 'Eu'
temp$actor[temp$actor=="Eu ???"] <- 'Eu'
temp$actor[temp$actor=="Eu/Netherlands"] <- 'Eu'
temp$actor[temp$actor=="Netherlands/Eu"] <- 'Eu'
temp$actor[temp$actor=="Ecuador ?"] <- 'Ecuador'
temp$actor[temp$actor=="Eggypt"] <- 'Egypt'
temp$actor[temp$actor=="El Slavador"] <- 'El Salvador'
temp$actor[temp$actor=="El Slavadore"] <- 'El Salvador'
temp$actor[temp$actor=="El Salvadr"] <- 'El Salvador'
temp$actor[temp$actor=="El Savador"] <- 'El Salvador'
temp$actor[temp$actor=="El Salvadore"] <- 'El Salvador'
temp$actor[temp$actor=="El Salvaldor"] <- 'El Salvador'

temp$actor[temp$actor=="Guatemale"] <- 'Guatemala'
temp$actor[temp$actor=="Guatemela"] <- 'Guatemala'
temp$actor[temp$actor=="Guatenala"] <- 'Guatemala'

temp$actor[temp$actor=="Macronesia"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Micronesia"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Fsm"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micronesai"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micrensia"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micronesa"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micronesua"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micreisa"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micronesiia"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micronesuia"] <- 'Federated States of Micronesia'
temp$actor[temp$actor=="Micrneisa"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Mironesia"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Micrinesia"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Microneusa"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Micronisia"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Miconesia"] <- 'Federated States Of Micronesia'
temp$actor[temp$actor=="Microneisa"] <- 'Federated States Of Micronesia'





temp$actor[temp$actor=="Fji"] <- "Fiji" 
temp$actor[temp$actor=="Fidji"] <- "Fiji" 
temp$actor[temp$actor=="Island"] <- "Iceland" 

temp$actor[temp$actor=="Icealand"] <- "Iceland" 
temp$actor[temp$actor=="Ielad"] <- "Iceland" 
temp$actor[temp$actor=="Iclaend"] <- "Iceland" 
temp$actor[temp$actor=="Icealnd"] <- "Iceland" 
temp$actor[temp$actor=="Icelnad"] <- "Iceland" 

temp$actor[temp$actor=="Icelamd"] <- "Iceland"
temp$actor[temp$actor=="Irak"] <- "Iraq"

temp$actor[temp$actor=="Jaacia"] <- "Jamaica" 
temp$actor[temp$actor=="Jamaicaa"] <- "Jamaica" 
temp$actor[temp$actor=="Jamaic"] <- "Jamaica" 
temp$actor[temp$actor=="Interntional Indian Treaty Council"] <- "International Indian Treaty Council"

temp$actor[temp$actor=="Janpan"] <- "Japan" 
temp$actor[temp$actor=="Jaoan"] <- "Japan" 
temp$actor[temp$actor=="Japana"] <- "Japan" 

temp$actor[temp$actor=="Israle"] <- "Israel" 

temp$actor[temp$actor=="Isreal"] <- "Israel" 
temp$actor[temp$actor=="Inodnesia"] <- "Indonesia" 
temp$actor[temp$actor=="Indnesia"] <- "Indonesia" 
temp$actor[temp$actor=="Indoensia"] <- "Indonesia" 
temp$actor[temp$actor=="Indinesia"] <- "Indonesia" 

temp$actor[temp$actor=="Iran (Islamic Republic Of)"] <- "Iran" 
temp$actor[temp$actor=="Lao"] <- "Laos" 
temp$actor[temp$actor=="Holy Seet"] <- 'Holy See'
temp$actor[temp$actor=="Holy Sea"] <- 'Holy See'
temp$actor[temp$actor=="Hoyl See"] <- 'Holy See'
temp$actor[temp$actor=="Vatican"] <- 'Holy See'

temp$actor[temp$actor=="Hondduras"] <- 'Honduras'



temp$actor[temp$actor=="Madagaskar"] <- 'Madagascar'

temp$actor[temp$actor=="Maledives"] <- 'Maldives'
temp$actor[temp$actor=="Madives"] <- 'Maldives'
temp$actor[temp$actor=="Malives"] <- 'Maldives'

temp$actor[temp$actor=="Malduves"] <- 'Maldives'
temp$actor[temp$actor=="Marshall Island"] <- 'Marshall Islands'
temp$actor[temp$actor=="Monocco"] <- 'Morocco'
temp$actor[temp$actor=="Morroco"] <- 'Morocco'
temp$actor[temp$actor=="Morrocco"] <- 'Morocco'
temp$actor[temp$actor=="Moroco"] <- 'Morocco'
temp$actor[temp$actor=="Monacco"] <- 'Monaco'
temp$actor[temp$actor=="Mocaco"] <- 'Monaco'
temp$actor[temp$actor=="Monacio"] <- 'Monaco'
temp$actor[temp$actor=="Mauritis"] <- 'Mauritius'
temp$actor[temp$actor=="Mauritus"] <- 'Mauritius'
temp$actor[temp$actor=="Monacp"] <- 'Monaco'
temp$actor[temp$actor=="Monoca"] <- 'Monaco'
temp$actor[temp$actor=="Mauritious"] <- 'Mauritius'
temp$actor[temp$actor=="Mauririus"] <- 'Mauritius'


temp$actor[temp$actor=="The former Yugoslav Republic of Macedonia"] <- 'North Macedonia'
temp$actor[temp$actor=="Macedonia"] <- 'North Macedonia'
temp$actor[temp$actor=="Mex"] <- 'Mexico'

temp$actor[temp$actor=="Mexi"] <- 'Mexico'

temp$actor[temp$actor=="New Zeeland"] <- 'New Zealand'
temp$actor[temp$actor=="New Zealnd"] <- 'New Zealand'
temp$actor[temp$actor=="New Zeland"] <- 'New Zealand'
temp$actor[temp$actor=="Nz"] <- 'New Zealand'
temp$actor[temp$actor=="Niaragua"] <- 'Nicaragua'
temp$actor[temp$actor=="Nacaragua"] <- 'Nicaragua'
temp$actor[temp$actor=="Niccaragua"] <- 'Nicaragua'
temp$actor[temp$actor=="Micaragua"] <- 'Nicaragua'
temp$actor[temp$actor=="New Norway"] <- 'Norway'
temp$actor[temp$actor=="Norways"] <- 'Norway'
temp$actor[temp$actor=="Norwa"] <- 'Norway'
temp$actor[temp$actor=="Neiru"] <- 'Nauru'
temp$actor[temp$actor=="Mauru"] <- 'Nauru'
temp$actor[temp$actor=="Nuaru"] <- 'Nauru'
temp$actor[temp$actor=="Oakstan"] <- 'Pakistan'
temp$actor[temp$actor=="Naura"] <- 'Nauru'
temp$actor[temp$actor=="Nigerai"] <- 'Nigeria'
temp$actor[temp$actor=="Palestina"] <- 'Palestine'
temp$actor[temp$actor=="Palstine"] <- 'Palestine'
temp$actor[temp$actor=="Palesitine"] <- 'Palestine'
temp$actor[temp$actor=="Paelstine"] <- 'Palestine'
temp$actor[temp$actor=="Paiesitne"] <- 'Palestine'
temp$actor[temp$actor=="Paestine"] <- 'Palestine'

temp$actor[temp$actor=="State Of Palestine"] <- 'Palestine'
temp$actor[temp$actor=="Papua New Genea"] <- 'Papua New Guinea'
temp$actor[temp$actor=="Papue New Guinea"] <- 'Papua New Guinea'
temp$actor[temp$actor=="Papuar New Guinea"] <- 'Papua New Guinea'
temp$actor[temp$actor=="Papua Guinea"] <- 'Papua New Guinea'
temp$actor[temp$actor=="Philppines"] <- 'Philippines'
temp$actor[temp$actor=="Phlippines"] <- 'Philippines'
temp$actor[temp$actor=="Phillippines"] <- 'Philippines'
temp$actor[temp$actor=="Philippuines"] <- 'Philippines'
temp$actor[temp$actor=="Philipppines"] <- 'Philippines'
temp$actor[temp$actor=="Philippines"] <- 'Philippines'
temp$actor[temp$actor=="Philipines"] <- 'Philippines'
temp$actor[temp$actor=="Phillippines"] <- 'Philippines'
temp$actor[temp$actor=="Phillipins"] <- 'Philippines'
temp$actor[temp$actor=="Phinillines"] <- 'Philippines'
temp$actor[temp$actor=="Philippenes"] <- 'Philippines'
temp$actor[temp$actor=="Philipines"] <- 'Philippines'
temp$actor[temp$actor=="Philiiipes"] <- 'Philippines'
temp$actor[temp$actor=="Philiipes"] <- 'Philippines'
temp$actor[temp$actor=="Philippnes"] <- 'Philippines'
temp$actor[temp$actor=="Philiipines"] <- 'Philippines'
temp$actor[temp$actor=="Philipinnes"] <- 'Philippines'
temp$actor[temp$actor=="Pilippines"] <- 'Philippines'
temp$actor[temp$actor=="Phiippiunes"] <- 'Philippines'
temp$actor[temp$actor=="Philipiees"] <- 'Philippines'
temp$actor[temp$actor=="Philpines"] <- 'Philippines'
temp$actor[temp$actor=="Phlipinnes"] <- 'Philippines'
temp$actor[temp$actor=="Pjhliinnes"] <- 'Philippines'
temp$actor[temp$actor=="Phalippines"] <- 'Philippines'
temp$actor[temp$actor=="Phiipines"] <- 'Philippines'
temp$actor[temp$actor=="Phiippines"] <- 'Philippines'
temp$actor[temp$actor=="Philipine"] <- 'Philippines'


temp$actor[temp$actor=="President"] <- 'President'
temp$actor[temp$actor=="Presidents"] <- 'President'
temp$actor[temp$actor=="Presidenty"] <- 'President'
temp$actor[temp$actor=="Preseident"] <- 'President'
temp$actor[temp$actor=="Presiedent"] <- 'President'
temp$actor[temp$actor=="Presisdent"] <- 'President'
temp$actor[temp$actor=="Presidnent"] <- 'President'
temp$actor[temp$actor=="Vice Presidnent"] <- 'President'
temp$actor[temp$actor=="Pre"] <- 'President'
temp$actor[temp$actor=="Predident"] <- 'President'
temp$actor[temp$actor=="Presiendt"] <- 'President'
temp$actor[temp$actor=="Presient"] <- 'President'
temp$actor[temp$actor=="Presdident"] <- 'President'
temp$actor[temp$actor=="Paraguy"] <- 'Paraguay'
temp$actor[temp$actor=="Republic of Corea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Koreaa"] <- 'Republic of Korea'
temp$actor[temp$actor=="Rep. of korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Rebublic of korea"] <- 'Republic of Korea'

temp$actor[temp$actor=="korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Repubic of Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Republic Of Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Republic Of Corea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Republic Of South Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Repubic Of Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Repubic Of South Corea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Repulic Of Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Rebublic Of Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Rep. Of Korea"] <- 'Republic of Korea'
temp$actor[temp$actor=="Russian"] <- 'Russia'
temp$actor[temp$actor=="Russian Federation"] <- 'Russia'
temp$actor[temp$actor=="Russian Fed."] <- 'Russia'
temp$actor[temp$actor=="Russiona Fed"] <- 'Russia'
temp$actor[temp$actor=="Russia"] <- 'Russia'
temp$actor[temp$actor=="Russa"] <- 'Russia'
temp$actor[temp$actor=="Rrussia"] <- 'Russia'



temp$actor[temp$actor=="Switzerand"] <- 'Switzerland'
temp$actor[temp$actor=="Sitzerland"] <- 'Switzerland'
temp$actor[temp$actor=="Sweitzerland"] <- 'Switzerland'
temp$actor[temp$actor=="Swtitzerland"] <- 'Switzerland'
temp$actor[temp$actor=="Seitzerland"] <- 'Switzerland'
temp$actor[temp$actor=="Siwterland"] <- 'Switzerland'
temp$actor[temp$actor=="Switzerlsnd"] <- 'Switzerland'
temp$actor[temp$actor=="Switzre<f6>And"] <- 'Switzerland'
temp$actor[temp$actor=="Swtzerand"] <- 'Switzerland'
temp$actor[temp$actor=="Switzerlnd"] <- 'Switzerland'
temp$actor[temp$actor=="Switzerlamd"] <- 'Switzerland'
temp$actor[temp$actor=="Swizterland"] <- 'Switzerland'
temp$actor[temp$actor=="Switzreöand"] <- 'Switzerland'
temp$actor[temp$actor=="Swirterland"] <- 'Switzerland'
temp$actor[temp$actor=="Swizerland"] <- 'Switzerland'





temp$actor[temp$actor=="Swtizerland"] <- 'Switzerland'
temp$actor[temp$actor=="Eswatini"] <- 'Swaziland'
temp$actor[temp$actor=="Trinidad"] <- 'Trinidad and Tobago'
temp$actor[temp$actor=="Tirinidad And Tobago"] <- 'Trinidad and Tobago'
temp$actor[temp$actor=="Trinidsd And Tobago"] <- 'Trinidad and Tobago'
temp$actor[temp$actor=="Trinidad And Robago"] <- 'Trinidad and Tobago'
temp$actor[temp$actor=="Trindad and Tobago"] <- 'Trinidad and Tobago'
temp$actor[temp$actor=="Triniidad and Tobago"] <- 'Trinidad and Tobago'

temp$actor[temp$actor=="Urugay"] <- 'Uruguay'
temp$actor[temp$actor=="Switerland"] <- 'Switzerland'
temp$actor[temp$actor=="Switzerlnad"] <- 'Switzerland'

temp$actor[temp$actor=="Singapur"] <- 'Singapore'
temp$actor[temp$actor=="Singapour"] <- 'Singapore'
temp$actor[temp$actor=="Singapuor"] <- 'Singapore'
temp$actor[temp$actor=="Sigapore"] <- 'Singapore'
temp$actor[temp$actor=="Sinagapore"] <- 'Singapore'
temp$actor[temp$actor=="Sinpapore"] <- 'Singapore'
temp$actor[temp$actor=="Singapre"] <- 'Singapore'
temp$actor[temp$actor=="Saingapore"] <- 'Singapore'
temp$actor[temp$actor=="Sibgapore"] <- 'Singapore'
temp$actor[temp$actor=="Singapor"] <- 'Singapore'
temp$actor[temp$actor=="Sinapore"] <- 'Singapore'
temp$actor[temp$actor=="Singapure"] <- 'Singapore'
temp$actor[temp$actor=="Sngapore"] <- 'Singapore'


temp$actor[temp$actor=="Sierra Leaone"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierra Lenane"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierra Leona"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierral Leone"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierra Leano"] <- 'Sierra Leone'
temp$actor[temp$actor=="SierraLeanoe"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierrre Leone"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierre Leone"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierra Lepne"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sierreleanoe"] <- 'Sierra Leone'
temp$actor[temp$actor=="San Lucia"] <- 'Saint Lucia'
temp$actor[temp$actor=="St Lucia"] <- 'Saint Lucia'
temp$actor[temp$actor=="Samo"] <- 'Samoa'
temp$actor[temp$actor=="Amoa"] <- 'Samoa'
temp$actor[temp$actor=="Samoa Obo Psids"] <- 'Samoa'
temp$actor[temp$actor=="Samaoa"] <- 'Samoa'


temp$actor[temp$actor=="Sout Africa"] <- 'South Africa'
temp$actor[temp$actor=="South Afric"] <- 'South Africa'
temp$actor[temp$actor=="Aouth Africa"] <- 'South Africa'
temp$actor[temp$actor=="South Arica"] <- 'South Africa'
temp$actor[temp$actor=="Southafrica"] <- 'South Africa'

temp$actor[temp$actor=="Sri-Lanka"] <- 'Sri Lanka'

temp$actor[temp$actor=="Sierre Leone"] <- 'Sierra Leone'
temp$actor[temp$actor=="Sirerra Leone"] <- 'Sierra Leone'
temp$actor[temp$actor=="Solemon Islands"] <- 'Solomon Islands'
temp$actor[temp$actor=="Salomon Islands"] <- 'Solomon Islands'
temp$actor[temp$actor=="Solomon"] <- 'Solomon Islands'
temp$actor[temp$actor=="Solomon Island"] <- 'Solomon Islands'
temp$actor[temp$actor=="Solomon Isldna"] <- 'Solomon Islands'
temp$actor[temp$actor=="Solomin Islands"] <- 'Solomon Islands'
temp$actor[temp$actor=="Solomon Isdlans"] <- 'Solomon Islands'
temp$actor[temp$actor=="Seychelle"] <- 'Seychelles'
temp$actor[temp$actor=="Seycheles"] <- 'Seychelles'
temp$actor[temp$actor=="Seychellles"] <- 'Seychelles'
temp$actor[temp$actor=="Sexchelles"] <- 'Seychelles'
temp$actor[temp$actor=="Seycelles"] <- 'Seychelles'
temp$actor[temp$actor=="Sechelles"] <- 'Seychelles'
temp$actor[temp$actor=="Seychalles?"] <- 'Seychelles'
temp$actor[temp$actor=="Sant Lucia"] <- 'Saint Lucia'
temp$actor[temp$actor=="Saudia Arabia"] <- 'Saudi Arabia'
temp$actor[temp$actor=="Suadi Arabia"] <- 'Saudi Arabia'
temp$actor[temp$actor=="Suad Ariabia"] <- 'Saudi Arabia'
temp$actor[temp$actor=="Saint Kitts And Nevis"] <- 'Saint Kitts'
temp$actor[temp$actor=="Saint Vincent And The Grenadines"] <- 'Saint Vincent'
temp$actor[temp$actor=="Syria"] <- 'Syrian Arabic Republic'
temp$actor[temp$actor=="Syrian Arab Republic"] <- 'Syrian Arabic Republic'
temp$actor[temp$actor=="Jamiaca"] <- 'Jamaica'
temp$actor[temp$actor=="Tansania"] <- 'Tanzania'
temp$actor[temp$actor=="United Of Republic Of Tanzania"] <- 'Tanzania'
temp$actor[temp$actor=="United Arb Emirates"] <- 'United Arab Emirates'
temp$actor[temp$actor=="United Repblic Of Tanzania"] <- 'Tanzania'
temp$actor[temp$actor=="United Arab Emitrates"] <- 'United Arab Emirates'


temp$actor[temp$actor=="Palistan"] <- 'Pakistan'
temp$actor[temp$actor=="Paksitan"] <- 'Pakistan'
temp$actor[temp$actor=="Pakistan"] <- 'Pakistan'
temp$actor[temp$actor=="Paskitan"] <- 'Pakistan'
temp$actor[temp$actor=="Paskitan angry"] <- 'Pakistan'


temp$actor[temp$actor=="Pakistanj"] <- 'Pakistan'
temp$actor[temp$actor=="Pakstian"] <- 'Pakistan'
temp$actor[temp$actor=="Paistan"] <- 'Pakistan'


temp$actor[temp$actor=="Akistan"] <- 'Pakistan'
temp$actor[temp$actor=="Paisan"] <- 'Pakistan'
temp$actor[temp$actor=="Turekey"] <- 'Turkey'
temp$actor[temp$actor=="Rurkey"] <- 'Turkey'
temp$actor[temp$actor=="Tureky"] <- 'Turkey'
temp$actor[temp$actor=="Turkiye"] <- 'Turkey'
temp$actor[temp$actor=="Türkiye"] <- 'Turkey'
temp$actor[temp$actor=="Turkyie"] <- 'Turkey'
temp$actor[temp$actor=="Turkye"] <- 'Turkey'
temp$actor[temp$actor=="Turky"] <- 'Turkey'

temp$actor[temp$actor=="Tuvaloa"] <- 'Tuvalu'
temp$actor[temp$actor=="Tuvala"] <- 'Tuvalu'
temp$actor[temp$actor=="Tuvalo"] <- 'Tuvalu'
temp$actor[temp$actor=="Tuvalus"] <- 'Tuvalu'
temp$actor[temp$actor=="Tongo"] <- 'Tonga'
temp$actor[temp$actor=="Rinidad And Tobago"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trinidad And Tobego"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trnidad And Tobago"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trinidad And Tobagp"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trinidad Nad Tobago"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trinidad & Tobago"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trinidad And Tobag"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trinidad And Tobgo"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trainidad And Tobago"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Trindad And Tobago"] <- 'Trinidad And Tobago'
temp$actor[temp$actor=="Triniidad And Tobago"] <- 'Trinidad And Tobago'




temp$actor[temp$actor=="Thalialand"] <- 'Thailand'
temp$actor[temp$actor=="Thaliand"] <- 'Thailand'
temp$actor[temp$actor=="Thailans"] <- 'Thailand'


temp$actor[temp$actor=="Vietnam"] <- 'Viet Nam'
temp$actor[temp$actor=="Vienam"] <- 'Viet Nam'
temp$actor[temp$actor=="Vietman"] <- 'Viet Nam'
temp$actor[temp$actor=="Vietmna"] <- 'Viet Nam'


temp$actor[temp$actor=="Duke"] <- 'Duke University'
temp$actor[temp$actor=="Venezuela"] <- 'Venezuela'
temp$actor[temp$actor=="Venzuela"] <- 'Venezuela'
temp$actor[temp$actor=="Venezuela (Bolivarian Republic Of)"] <- 'Venezuela'
temp$actor[temp$actor=="Veenzueal"] <- 'Venezuela'

### still needs to be checked in real data
temp$actor[temp$actor=="Kenya??"] <- 'Kenya'


## alliances
temp$actor[temp$actor=="G77+china"] <- 'G77+China'
temp$actor[temp$actor=="G77+China"] <- 'G77+China'
temp$actor[temp$actor=="G77 And Chia"] <- 'G77+China'
temp$actor[temp$actor=="G77"] <- 'G77+China'
temp$actor[temp$actor=="G77 + China"] <- 'G77+China'
temp$actor[temp$actor=="G77/China"] <- 'G77+China'



## UN Bodies
temp$actor[startsWith(temp$actor, "Fac")] <- "Facilitator"

temp$actor[temp$actor=="Facicilator"] <- 'Facilitator'
temp$actor[temp$actor=="Faciliator"] <- 'Facilitator'
temp$actor[temp$actor=="Faciliattor"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitaot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitarot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitatoe"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitators"] <- 'Facilitator'
temp$actor[temp$actor=="Facilititotor"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltiator"] <- 'Facilitator'
temp$actor[temp$actor=="Facitilator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitaor"] <- 'Facilitator'
temp$actor[temp$actor=="Faclilitator"] <- 'Facilitator'
temp$actor[temp$actor=="Faciitator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitapr"] <- 'Facilitator'
temp$actor[temp$actor=="Facliitator"] <- 'Facilitator'
temp$actor[temp$actor=="Faclitator"] <- 'Facilitator'
temp$actor[temp$actor=="Failitato"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltiat"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltiatos"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaito"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Faciilitator"] <- 'Facilitator'
temp$actor[temp$actor=="Faciliato"] <- 'Facilitator'
temp$actor[temp$actor=="Faciitt"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltator"] <- 'Facilitator'
temp$actor[temp$actor=="Faclitato"] <- 'Facilitator'
temp$actor[temp$actor=="Facilair"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitiatp"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitor"] <- 'Facilitator'
temp$actor[temp$actor=="Faccilitaot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaitr"] <- 'Facilitator'
temp$actor[temp$actor=="Faciitt"] <- 'Facilitator'
temp$actor[temp$actor=="Facilator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitait"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitaotr"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitaro"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitat"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitato"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitiaot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitorato"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitorot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitotor"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltitator"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilitaot"] <- 'Facilitator'
temp$actor[temp$actor=="Ffaciliator"] <- 'Facilitator'
temp$actor[temp$actor=="Fscilitator"] <- 'Facilitator'
temp$actor[temp$actor=="Faciliat"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitaion"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator Netherlands"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator. South Africa"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitatot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitot"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitrator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitro"] <- 'Facilitator'
temp$actor[temp$actor=="Facilittor"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltat"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltato"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltiato"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltoroe"] <- 'Facilitator'
temp$actor[temp$actor=="Facitat"] <- 'Facilitator'
temp$actor[temp$actor=="Facitlat"] <- 'Facilitator'
temp$actor[temp$actor=="Faclitiato"] <- 'Facilitator'
temp$actor[temp$actor=="Faclitior"] <- 'Facilitator'
temp$actor[temp$actor=="Faculotaro"] <- 'Facilitator'
temp$actor[temp$actor=="Fci"] <- 'Facilitator'
temp$actor[temp$actor=="Fciitato"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilitors"] <- 'Facilitator'
temp$actor[temp$actor=="Fecaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Fscilitaot"] <- 'Facilitator'
temp$actor[temp$actor=="Fsci"] <- 'Facilitator'
temp$actor[temp$actor=="Faci"] <- 'Facilitator'
temp$actor[temp$actor=="Faaci"] <- 'Facilitator'
temp$actor[temp$actor=="Facclitator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilit"] <- 'Facilitator'
temp$actor[temp$actor=="Facliator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitatr"] <- 'Facilitator'
temp$actor[temp$actor=="Faclitaot"] <- 'Facilitator'
temp$actor[temp$actor=="Facitaotr"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaitp"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitora"] <- 'Facilitator'
temp$actor[temp$actor=="Facliiat"] <- 'Facilitator'
temp$actor[temp$actor=="Facliator"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaitaro"] <- 'Facilitator'
temp$actor[temp$actor=="Fciliataor"] <- 'Facilitator'
temp$actor[temp$actor=="Facliiator"] <- 'Facilitator'
temp$actor[temp$actor=="Faciltaot"] <- 'Facilitator'
temp$actor[temp$actor=="Facciliatort"] <- 'Facilitator'
temp$actor[temp$actor=="Facilait"] <- 'Facilitator'
temp$actor[temp$actor=="Facitliat"] <- 'Facilitator'
temp$actor[temp$actor=="Facilate"] <- 'Facilitator'
temp$actor[temp$actor=="Facilte"] <- 'Facilitator'
temp$actor[temp$actor=="Failiatoe"] <- 'Facilitator'
temp$actor[temp$actor=="Faciate"] <- 'Facilitator'
temp$actor[temp$actor=="Facilator,"] <- 'Facilitator'
temp$actor[temp$actor=="Facitliato"] <- 'Facilitator'
temp$actor[temp$actor=="Fa"] <- 'Facilitator'
temp$actor[temp$actor=="Facliitato"] <- 'Facilitator'
temp$actor[temp$actor=="Acilaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Ficiiator"] <- 'Facilitator'
temp$actor[temp$actor=="Faaicltor"] <- 'Facilitator'
temp$actor[temp$actor=="Faiator"] <- 'Facilitator'
temp$actor[temp$actor=="Faiclaior"] <- 'Facilitator'
temp$actor[temp$actor=="Faicliator"] <- 'Facilitator'
temp$actor[temp$actor=="Failiator"] <- 'Facilitator'
temp$actor[temp$actor=="Faliciatr"] <- 'Facilitator'
temp$actor[temp$actor=="Falicitator"] <- 'Facilitator'
temp$actor[temp$actor=="Fcacilaitpr"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilaitr"] <- 'Facilitator'
temp$actor[temp$actor=="Fcliitator"] <- 'Facilitator'
temp$actor[temp$actor=="Fcliitr"] <- 'Facilitator'
temp$actor[temp$actor=="Faiciliator"] <- 'Facilitator'
temp$actor[temp$actor=="Faicliatoe"] <- 'Facilitator'
temp$actor[temp$actor=="Faiclitor"] <- 'Facilitator'
temp$actor[temp$actor=="Failatp"] <- 'Facilitator'
temp$actor[temp$actor=="Fciiator"] <- 'Facilitator'
temp$actor[temp$actor=="Fciliator"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilitator"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilitor"] <- 'Facilitator'
temp$actor[temp$actor=="Fcliaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Ffacliiator"] <- 'Facilitator'
temp$actor[temp$actor=="Fsciitotor"] <- 'Facilitator'
temp$actor[temp$actor=="Dailator"] <- 'Facilitator'
temp$actor[temp$actor=="Nafci"] <- 'Facilitator'
temp$actor[temp$actor=="Facilaltor"] <- 'Facilitator'
temp$actor[temp$actor=="Faicliatr"] <- 'Facilitator'
temp$actor[temp$actor=="Failaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Failaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Failciato"] <- 'Facilitator'
temp$actor[temp$actor=="Failtaot"] <- 'Facilitator'
temp$actor[temp$actor=="Failitator"] <- 'Facilitator'
temp$actor[temp$actor=="Falictato"] <- 'Facilitator'
temp$actor[temp$actor=="Faliitator"] <- 'Facilitator'
temp$actor[temp$actor=="Fcaialtor"] <- 'Facilitator'
temp$actor[temp$actor=="Fcailtaot"] <- 'Facilitator'
temp$actor[temp$actor=="Fciaitor"] <- 'Facilitator'
temp$actor[temp$actor=="Fcilator"] <- 'Facilitator'
temp$actor[temp$actor=="Fciltiato"] <- 'Facilitator'
temp$actor[temp$actor=="Fciltor"] <- 'Facilitator'
temp$actor[temp$actor=="Fclitor"] <- 'Facilitator'
temp$actor[temp$actor=="Fsciliator"] <- 'Facilitator'
temp$actor[temp$actor=="Fsilitor"] <- 'Facilitator'
temp$actor[temp$actor=="Fscilitat"] <- 'Facilitator'
temp$actor[temp$actor=="Aciltiaotr"] <- 'Facilitator'
temp$actor[temp$actor=="New Facilitator"] <- 'Facilitator'
temp$actor[temp$actor=="FFacilitaor"] <- 'Facilitator'
temp$actor[temp$actor=="Acilitator"] <- 'Facilitator'
temp$actor[temp$actor=="Aciltiator"] <- 'Facilitator'
temp$actor[temp$actor=="Faicilaltor"] <- 'Facilitator'
temp$actor[temp$actor=="Failitaot"] <- 'Facilitator'
temp$actor[temp$actor=="Failito"] <- 'Facilitator'
temp$actor[temp$actor=="Failtiator"] <- 'Facilitator'
temp$actor[temp$actor=="Failtot"] <- 'Facilitator'
temp$actor[temp$actor=="Fciltator"] <- 'Facilitator'
temp$actor[temp$actor=="Fclitar"] <- 'Facilitator'
temp$actor[temp$actor=="Ffacilitaor"] <- 'Facilitator'
temp$actor[temp$actor=="Fciltaot"] <- 'Facilitator'
temp$actor[temp$actor=="Mgr Chair"] <- 'Facilitator'
temp$actor[temp$actor=="Chair In Mgr"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator Abmts"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator On Eias"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator Cb Tt"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator Of Abmt"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator Of Eia"] <- 'Facilitator'
temp$actor[temp$actor=="Facilitator On Cb & Tmt"] <- 'Facilitator'
temp$actor[temp$actor=="Chair"] <- 'Facilitator'
temp$actor[temp$actor=="Cchair"] <- 'Facilitator'
temp$actor[temp$actor=="Chai"] <- 'Facilitator'
temp$actor[temp$actor=="Chair- Gabriele Wanli"] <- 'Facilitator'
temp$actor[temp$actor=="Chair- Nulifer Oral"] <- 'Facilitator'
temp$actor[temp$actor=="Chair (Eden Charles)"] <- 'Facilitator'
temp$actor[temp$actor=="Chair (Gabi Wanli)"] <- 'Facilitator'
temp$actor[temp$actor=="Chair (Gabi)"] <- 'Facilitator'
temp$actor[temp$actor=="Chair (Gabriele Goettsche-Wanli)"] <- 'Facilitator'
temp$actor[temp$actor=="Chair 1"] <- 'Facilitator'
temp$actor[temp$actor=="Chair 2"] <- 'Facilitator'
temp$actor[temp$actor=="Chair/Eden Charles"] <- 'Facilitator'
temp$actor[temp$actor=="Chair/Wani"] <- 'Facilitator'
temp$actor[temp$actor=="Chair/Wanl"] <- 'Facilitator'
temp$actor[temp$actor=="Chair/Wanli"] <- 'Facilitator'
temp$actor[temp$actor=="Chairs"] <- 'Facilitator'
temp$actor[temp$actor=="Char"] <- 'Facilitator'
temp$actor[temp$actor=="Chauir"] <- 'Facilitator'
temp$actor[temp$actor=="Chaur"] <- 'Facilitator'
temp$actor[temp$actor=="Chiair"] <- 'Facilitator'
temp$actor[temp$actor=="Co-Chair"] <- 'Facilitator'
temp$actor[temp$actor=="Nfaci"] <- 'Facilitator'



temp$actor[temp$actor=="secretary	"] <- 'Secretariat'
temp$actor[temp$actor=="Secretary"] <- 'Secretariat'
temp$actor[temp$actor=="Secreatry"] <- 'Secretariat'
temp$actor[temp$actor=="Secretrary?"] <- 'Secretariat'
temp$actor[temp$actor=="Secreatary?"] <- 'Secretariat'
temp$actor[temp$actor=="Secreatary"] <- 'Secretariat'
temp$actor[temp$actor=="Secreatrait"] <- 'Secretariat'
temp$actor[temp$actor=="Secrestariat"] <- 'Secretariat'
temp$actor[temp$actor=="Secretarait"] <- 'Secretariat'
temp$actor[temp$actor=="Sec"] <- 'Secretariat'
temp$actor[temp$actor=="Seceretary General"] <- 'Secretariat'  

temp$actor[temp$actor=="Sg Of The Conference"] <- 'Secretariat'
temp$actor[temp$actor=="Secretariat General Of The conference"] <- 'Secretariat'
temp$actor[temp$actor=="Secretary General Of The Conference"] <- 'Secretariat'
temp$actor[temp$actor=="Sg"] <- 'Secretariat'
temp$actor[temp$actor=="Office Of Legal Affairs, Secretary General Of The Conference"] <- 'Secretariat'
temp$actor[temp$actor=="Office Of Legal Affairs"] <- 'Secretariat'
temp$actor[temp$actor=="Secretariat Un Legal Council"] <- 'Secretariat'
temp$actor[temp$actor=="Director Of Legal Affairs, Divison Of Law Of The Sea"] <- 'UNDOALOS'
temp$actor[temp$actor=="Doalos"] <- 'UNDOALOS'
temp$actor[temp$actor=="Undoals"] <- 'UNDOALOS'
temp$actor[temp$actor=="DOALOS"] <- 'UNDOALOS'
temp$actor[temp$actor=="UDOALOS"] <- 'UNDOALOS'
temp$actor[temp$actor=="UNDUALUS"] <- 'UNDOALOS'
temp$actor[temp$actor=="UNDOALDOS"] <- 'UNDOALOS'
temp$actor[temp$actor=="Un Environment"] <- 'UNEP'
temp$actor[temp$actor=="Unep Wcmc"] <- 'Unep-Wcmc'

temp$actor[temp$actor=="Rena"] <- 'President'
temp$actor[temp$actor=="Rea"] <- 'President'
temp$actor[temp$actor=="Rnea"] <- 'President'

temp$actor[temp$actor=="president"] <- 'President'
temp$actor[temp$actor=="Preident"] <- 'President'
temp$actor[temp$actor=="Presidency"] <- 'President'
temp$actor[temp$actor=="Preesident"] <- 'President'
temp$actor[temp$actor=="Presidnet"] <- 'President'
temp$actor[temp$actor=="Prsident"] <- 'President'

temp$actor[temp$actor=="Ioc Lucy Scott"] <- 'Ioc-Unesco'


temp$actor[temp$actor=="Department Of Economic And Social Affairs"] <- 'UNDESA'
temp$actor[temp$actor=="Secretariat Of The Convention On Biological Diversity"] <- 'CBD'
temp$actor[temp$actor=="Convention on Biological Diversity"] <- 'CBD'
temp$actor[temp$actor=="Cbd"] <- 'CBD'
temp$actor[temp$actor=="Secretariat Of The Convention On The Conservation Of Migratory Species Of Wild Animals"] <- 'CMS'
temp$actor[temp$actor=="United Nations Environment Programme"] <- 'UNEP'
temp$actor[temp$actor=="Convention On The Conservation Of Migratory Species Of Wild Animals"] <- 'CMS'


### NGOs "Abbrv"
temp$actor[temp$actor=="High Sea Alliance"] <- 'HSA'
temp$actor[temp$actor=="High Seas Alliance"] <- 'HSA'
temp$actor[temp$actor=="Has"] <- 'HSA'
temp$actor[temp$actor=="ICEL (intergovernmnetal council on environmental law)"] <- 'ICEL'
temp$actor[temp$actor=="International Council of Environmental Law"] <- 'ICEL'
temp$actor[temp$actor=="International Council Of Environental Law"] <- 'ICEL'
temp$actor[temp$actor=="International Council For Environmetnal Law"] <- 'ICEL'
temp$actor[temp$actor=="International Council For Environmental Law"] <- 'ICEL'
temp$actor[temp$actor=="international council for environmental law"] <- 'ICEL'
temp$actor[temp$actor=="International Council Of Environmental Law"] <- 'ICEL'
temp$actor[temp$actor=="Ciel"] <- 'ICEL'
temp$actor[temp$actor=="Environmental Council Of Environmental Law"] <- 'ICEL'
temp$actor[temp$actor=="Icel (Intergovernmnetal Council On Environmental Law)"] <- 'ICEL'
temp$actor[temp$actor=="International Seabed Authority"] <- 'ISA'
temp$actor[temp$actor=="Isa Secretariat"] <- 'ISA'
temp$actor[temp$actor=="Deep Ocean Stewardship Initiative"] <- 'DOSI'
temp$actor[temp$actor=="Deep Ocean Stewardship"] <- 'DOSI'
temp$actor[temp$actor=="Dosi (?)"] <- 'DOSI'
temp$actor[temp$actor=="Institute for Sustainable Development and International Relations"] <- 'IDDRI'
temp$actor[temp$actor=="Institut du d?veloppement durable et des relations internationales"] <- 'IDDRI'
temp$actor[temp$actor=="Institute For Advanced Sustainability Studies E.V."] <- 'IASS'
temp$actor[temp$actor=="Natural Resources Defence Council, Inc"] <- 'NRDC'
temp$actor[temp$actor=="Natural Resources Defence Council"] <- 'NRDC'
temp$actor[temp$actor=="Natural Resources Defence Council"] <- 'NRDC'
temp$actor[temp$actor=="Natural Resources Defense Council"] <- 'NRDC'
temp$actor[temp$actor=="Natural Resources Defense"] <- 'NRDC'
temp$actor[temp$actor=="Natural Defense Council on Hsa"] <- 'NRDC'
temp$actor[temp$actor=="Naturl Resources Defense"] <- 'NRDC'
temp$actor[temp$actor=="Nldc"] <- 'NRDC'

temp$actor[temp$actor=="Ngo"] <- 'Ngos'





temp$actor[temp$actor=="Irdc"] <- 'NRDC'
temp$actor[temp$actor=="Nippon"] <- 'Nippon Foundation'
temp$actor[temp$actor=="International Union For the Conservation Of Nature"] <- 'IUCN'
temp$actor[temp$actor=="Iunc"] <- 'IUCN'
temp$actor[temp$actor=="Idri"] <- 'IDDRI'
temp$actor[temp$actor=="Ocean Care"] <- 'Oceancare'
temp$actor[temp$actor=="Sasakawa Peace Foundation"] <- 'Sasakawa'
temp$actor[temp$actor=="International Coastal And Ocean Organization"] <- 'ICO'


### IGOs
temp$actor[temp$actor=="North East Atlantic Fisheries Commission"] <- 'NEAFC'
temp$actor[temp$actor=="North East Atlantic Fishery Commission"] <- 'NEAFC'
temp$actor[temp$actor=="International Seabed Authority"] <- 'ISA'
temp$actor[temp$actor=="International Maritime Organization"] <- 'IMO'
temp$actor[temp$actor=="International Oceanographic Commission"] <- 'IOC'
temp$actor[temp$actor=="Unesco"] <- 'IOC'
temp$actor[temp$actor=="Ioc"] <- 'IOC'
temp$actor[temp$actor=="Ioc Unesco"] <- 'IOC'
temp$actor[temp$actor=="Unesco-Ioc"] <- 'IOC'
temp$actor[temp$actor=="Ioc-Unesco"] <- 'IOC'
temp$actor[temp$actor=="Iitc"] <- 'International Indian Treaty Council'




temp$actor[temp$actor=="Comisi?n Permanente Del Paclfico Sur"] <- 'CPPS'
temp$actor[temp$actor=="Cpps"] <- 'CPPS'
temp$actor[temp$actor=="North-West Atlantic Fisheries Commission"] <- 'NAFO'
temp$actor[temp$actor=="North Pacific Fisheries Commission"] <- 'NPFC'
temp$actor[temp$actor=="Nplc"] <- 'ICPC'
temp$actor[temp$actor=="Ospar Commission For The Protection Of The Marine Environment Of The North-East Atlantic"] <- 'OSPAR'
temp$actor[temp$actor=="Secretariat Of The Pacific Regional Environment Programme"] <- 'SPREP'
temp$actor[temp$actor=="Western And Central Pacific Fisheries Commission"] <- 'WCPFC'
temp$actor[temp$actor=="Asian-African Legal Consultative Organization"] <- 'AALCO'
temp$actor[temp$actor=="International Council For The Exploration Of The Sea"] <- 'ICES'
temp$actor[temp$actor=="Global Environment Facility"] <- 'GEF'
temp$actor[temp$actor=="World Intellectual Property Organization "] <- 'WIPO'
temp$actor[temp$actor=="Isa"] <- 'ISA'
temp$actor[temp$actor=="international cabel protection committee"] <- 'ICPC'
temp$actor[temp$actor=="international cabel protection committee"] <- 'ICPC'
temp$actor[temp$actor=="International Cabel Protection Committee"] <- 'ICPC'
temp$actor[temp$actor=="International Cable Protection Committee"] <- 'ICPC'
temp$actor[temp$actor=="The International Calble Protection Committee"] <- 'ICPC'
temp$actor[temp$actor=="International Cable Protection Committee Limited"] <- 'ICPC'
temp$actor[temp$actor=="The International Cable Protection Committee"] <- 'ICPC'
temp$actor[temp$actor=="Nhm"] <- 'Natural History Museum'
temp$actor[temp$actor=="Pacific Community"] <- 'SPC'
temp$actor[temp$actor=="Duncna"] <- 'Duncan'
temp$actor[temp$actor=="Pew Charitable Trust"] <- 'Pew'
temp$actor[temp$actor=="Credentials Committe"] <- 'Credentials Committee'
temp$actor[temp$actor=="Credentials Commitee ireland"] <- 'Credentials Committee'
temp$actor[temp$actor=="Credentals Commitee ireland"] <- 'Credentials Committee'
temp$actor[temp$actor=="Nyiue"] <- 'Niue'

### New changes - actor cleaning
temp$actor[temp$actor=="140"] <- '140 Participants'
temp$actor[temp$actor=="5"] <- '144 Participants'
temp$actor[temp$actor=="All Actors"] <- 'All'
temp$actor[temp$actor=="Aosis"] <- 'Antigua And Barbuda'
temp$actor[temp$actor=="Argentina Ono Clam"] <- 'Argentina Obo Clam'
temp$actor[temp$actor=="Argentina; Martin Mainero"] <- 'Argentina'
temp$actor[temp$actor=="Aughing"] <- 'Laughing'
temp$actor[temp$actor=="Babb Riley, Barbados"] <- 'Barbados'
temp$actor[temp$actor=="Emd"] <- 'End'
temp$actor[temp$actor=="End Of Informal Informals"] <- 'End'
temp$actor[temp$actor=="Ends"] <- 'End'
temp$actor[temp$actor=="Partcipants"] <- 'Participants'
temp$actor[temp$actor=="Particpants"] <- 'Participants'
temp$actor[temp$actor=="Paticipnats"] <- 'Participants'
temp$actor[temp$actor=="Where They Are"] <- 'All'



temp$actor[temp$actor=="Psdis"] <- 'Psids'
temp$actor[temp$actor=="Room"] <- 'All Laughing'
temp$actor[temp$actor=="Room Clapping"] <- 'All Clapping'
temp$actor[temp$actor=="Room Kughing"] <- 'All Laughing'
temp$actor[temp$actor=="Room Laughing"] <- 'All Laughing'
temp$actor[temp$actor=="Room Laughng"] <- 'All Laughing'
temp$actor[temp$actor=="Room Laughnig"] <- 'All Laughing'
temp$actor[temp$actor=="Waving"] <- 'All Waving'
temp$actor[temp$actor=="Silcence"] <- 'Silence'
temp$actor[temp$actor=="Sielnce"] <- 'Silence'
temp$actor[temp$actor=="Silence - Tech Issue"] <- 'Silence'
temp$actor[temp$actor=="Silence, No Tine"] <- 'Silence'
temp$actor[temp$actor=="Silene"] <- 'Silence'
temp$actor[temp$actor=="Silnece"] <- 'Silence'
temp$actor[temp$actor=="Africa"] <- 'African Group'
temp$actor[temp$actor=="Microesia Obo Psdis"] <- 'Micronesia Obo Psids'
temp$actor[temp$actor=="Obo G77+china"] <- 'Cuba'
temp$actor[temp$actor=="Several Speakers"] <- 'Several Actors'
temp$actor[temp$actor=="Tech"] <- 'Technical Problem'
temp$actor[temp$actor=="Tech Issue"] <- 'Technical Problem'
temp$actor[temp$actor=="Tech Issues"] <- 'Technical Problem'
temp$actor[temp$actor=="Unknown"] <- 'Nz?Aus?'
temp$actor[temp$actor=="Nz?Aus?"] <- 'Unknown'

temp$comment_obs[temp$actor=="Pakistan Angry"] <- 'seems angry'
temp$actor[temp$actor=="Pakistan Angry"] <- 'Pakistan'

temp$comment_obs[temp$actor=="Russia Leaving"] <- 'Leaving'
temp$actor[temp$actor=="Russia Leaving"] <- 'Russia'


temp$actor <- str_to_lower(temp$actor)

bbnj <- temp

bbnj <- bbnj[order(bbnj$author, bbnj$id_num), ]
my_vec <- bbnj$actor
new_vec <- vector(length = length(my_vec))
for (i in seq_along(my_vec)) {
  if (!is.na(my_vec[i])) current <- my_vec[i]
  new_vec[i] <- current
  
}

bbnj[["actor"]] <- new_vec
