#this code was written by Simon Fellinger
bbnj <- mutate(bbnj, draft =ifelse (IGC == 1, "http://undocs.org/en/A/CONF.232/2018/3",
                                    ifelse (IGC == 2, "http://undocs.org/A/CONF.232/2019/1", 
                                            ifelse (IGC == 3, "https://undocs.org/a/conf.232/2019/6",
                                                    ifelse (IGC == 4, "https://undocs.org/en/a/conf.232/2020/3",
                                                            ifelse (IGC == 5, "https://undocs.org/A/CONF.232/2022/5",
                                                                    ifelse (IGC == 5.2, "https://undocs.org/a/conf.232/2023/2", 
                                                                            ifelse(IGC == 5.3, "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/draft_agreement_advanced_unedited_for_posting_v1.pdf",
                                                                                   "no draft"))))))))

## adding enb reports for the related negotiating day:
# IGC 1
bbnj <- mutate(bbnj, enb =ifelse (date == "2018-09-04", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-21",
                                  ifelse (date == "2018-09-05", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-20",
                                          ifelse (date == "2018-09-06", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-19",
                                                  ifelse (date == "2018-09-07", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-18",
                                                          ifelse (date == "2018-09-10", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-17",
                                                                  ifelse (date == "2018-09-11", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-16",
                                                                          ifelse (date == "2018-09-12", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-15",
                                                                                  ifelse (date == "2018-09-13", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-14",
                                                                                          ifelse (date == "2018-09-14", "https://enb.iisd.org/events/1st-session-intergovernmental-conference-igc-international-legally-binding-instrument-13",
                                                                                                  "NA"))))))))))

bbnj <- mutate(bbnj, enb =ifelse (date == "2019-03-25", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-3",
                                  ifelse (date == "2019-03-26", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-7",
                                          ifelse (date == "2019-03-27", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-6",
                                                  ifelse (date == "2019-03-28", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-5",
                                                          ifelse (date == "2019-03-29", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-4",
                                                                  ifelse (date == "2019-04-01", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-2",
                                                                          ifelse (date == "2019-04-02", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-1",
                                                                                  ifelse (date == "2019-04-03", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-0",
                                                                                          ifelse (date == "2019-04-04", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily",
                                                                                                  ifelse (date == "2019-04-05", "https://enb.iisd.org/events/2nd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine-9", enb)))))))))))

bbnj <- mutate(bbnj, enb =ifelse (date == "2019-08-19", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-7",
                                  ifelse (date == "2019-08-20", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-6",
                                          ifelse (date == "2019-08-21", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-5",
                                                  ifelse (date == "2019-08-22", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-4",
                                                          ifelse (date == "2019-08-23", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-3",
                                                                  ifelse (date == "2019-08-26", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-2",
                                                                          ifelse (date == "2019-08-27", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-1",
                                                                                  ifelse (date == "2019-08-28", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily-0",
                                                                                          ifelse (date == "2019-08-29", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine/daily",
                                                                                                  ifelse (date == "2019-08-30", "https://enb.iisd.org/events/3rd-session-intergovernmental-conference-igc-conservation-and-sustainable-use-marine-9", enb)))))))))))

bbnj <- mutate (bbnj, enb =ifelse( date == "2022-03-07", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-7Mar2022",
                                   ifelse (date == "2022-03-08", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-8Mar2022",
                                           ifelse (date == "2022-03-09", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-9Mar2022",
                                                   ifelse (date == "2022-03-10", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-10Mar2022",
                                                           ifelse (date == "2022-03-11", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-11Mar2022",
                                                                   ifelse (date == "2022-03-14", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-14Mar2022",
                                                                           ifelse (date == "2022-03-15", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-15Mar2022",
                                                                                   ifelse (date == "2022-03-16", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-16Mar2022",
                                                                                           ifelse (date == "2022-03-17", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-17Mar2022",
                                                                                                   ifelse (date == "2022-03-18", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc4-18Mar2022", enb)))))))))))

bbnj <- mutate (bbnj, enb =ifelse( date == "2022-08-15", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-15aug2022",
                                   ifelse ( date == "2022-08-16", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-16aug2022",
                                            ifelse (date == "2022-08-17", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-17aug2022",
                                                    ifelse (date == "2022-08-18", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-18aug2022",
                                                            ifelse (date == "2022-08-19", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-19aug2022",
                                                                    ifelse (date == "2022-08-22", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-22aug2022",
                                                                            ifelse (date == "2022-08-23", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-23aug2022",
                                                                                    ifelse (date == "2022-08-24", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-24aug2022",
                                                                                            ifelse (date == "2022-08-25", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-daily-report-25aug2022",
                                                                                                    ifelse (date == "2022-08-26", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-26aug2022", enb)))))))))))

bbnj <- mutate (bbnj, enb =ifelse (date == "2023-02-20", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-20feb2022",
                                   ifelse (date == "2023-02-21", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-21feb2022",
                                           ifelse (date == "2023-02-22", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-22feb2022",
                                                   ifelse (date == "2023-02-23", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-23feb2022",
                                                           ifelse (date == "2023-02-24", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-24feb2022",
                                                                   ifelse (date == "2023-02-27", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-27feb2022",
                                                                           ifelse (date == "2023-02-28", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-28feb2023",
                                                                                   ifelse (date == "2023-03-01", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-1mar2023",
                                                                                           ifelse (date == "2023-03-02", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-daily-report-2mar2023",
                                                                                                   ifelse (date == "2023-03-03", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-3Mar2023",
                                                                                                           ifelse (date == "2023-03-04", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-resumed-3Mar2023", enb))))))))))))

bbnj <- mutate (bbnj, enb =ifelse (date == "2023-06-19", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-further-resumed-19jun23",
                                   ifelse (date == "2023-06-20", "https://enb.iisd.org/marine-biodiversity-beyond-national-jurisdiction-bbnj-igc5-further-resumed-20jun23", enb)))


#adding webcasts
#IGC1

bbnj <- mutate (bbnj, webcast =ifelse (date == "2018-09-04" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1o/k1o8lwir7b?_gl=1*mtynx7*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjAuMTY4Nzk0NjcxMi4wLjAuMA..",
                                       ifelse (date == "2018-09-04" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1w/k1w0cuzp8a?_gl=1*dwblxs*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjAuMTY4Nzk0NjczMi4wLjAuMA..",
                                               ifelse (date == "2018-09-05" &(time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1u/k1uuusxk80?_gl=1*sy1src*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjAuMTY4Nzk0Njc1Mi4wLjAuMA..",
                                                       ifelse (date == "2018-09-05" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1v/k1v62umsjl?_gl=1*ctfabi*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Njc5Mi4wLjAuMA..",
                                                               ifelse (date == "2018-09-06" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1h/k1hdwm2cx4?_gl=1*1fs8kow*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NjgxNi4wLjAuMA..",
                                                                       ifelse (date == "2018-09-06" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1n/k1n4wpecs0?_gl=1*1biw8va*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Njg5OC4wLjAuMA..",
                                                                               ifelse (date == "2018-09-07" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1g/k1gtwyfh6n?_gl=1*1c6khkd*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Njk2NS4wLjAuMA..",
                                                                                       ifelse (date == "2018-09-07" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1w/k1wrhg0l58?_gl=1*sqglb1*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzA0Ny4wLjAuMA..",
                                                                                               ifelse (date == "2018-09-10" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1r/k1r3bnauht?_gl=1*18e3wk2*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzEyMS4wLjAuMA..",
                                                                                                       ifelse (date == "2018-09-10" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1x/k1xauhvme1?_gl=1*yfq8ng*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzE3My4wLjAuMA..",
                                                                                                               ifelse (date == "2018-09-11" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1t/k1t0lij62j?_gl=1*zq6zp0*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzIzOS4wLjAuMA..",
                                                                                                                       ifelse (date == "2018-09-11" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1u/k1uwlymn08?_gl=1*18lxt0w*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzM4Ni4wLjAuMA..",
                                                                                                                               ifelse (date == "2018-09-12" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1z/k1z0squ0ev?_gl=1*1i0dur1*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzUzNC4wLjAuMA..",
                                                                                                                                       ifelse (date == "2018-09-12" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k1u/k1u01ort97?_gl=1*1ro46w8*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzYwMC4wLjAuMA..",
                                                                                                                                               ifelse (date == "2018-09-13" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1c/k1c6w4dffa?_gl=1*1sc7t60*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Nzc2Ni4wLjAuMA..",
                                                                                                                                                       ifelse (date == "2018-09-13" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k19/k19m22h2s1?_gl=1*17y7nyf*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Nzc4MS4wLjAuMA..",
                                                                                                                                                               ifelse (date == "2018-09-14" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1b/k1bwmqemok?_gl=1*1hdx1r4*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Nzg1Ni4wLjAuMA..",
                                                                                                                                                                       ifelse (date == "2018-09-14" & (time >= "15:00:00" & time <= "18:00:00"), "https://media.un.org/en/asset/k16/k161pwpdzj?_gl=1*1lv4b0n*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0NzkxNC4wLjAuMA..",
                                                                                                                                                                               ifelse (date == "2018-09-17" & (time >= "10:00:00" & time <= "13:00:00"), "https://media.un.org/en/asset/k1u/k1u388ip82?_gl=1*er3oqq*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0Nzk3Mi4wLjAuMA..", 
                                                                                                                                                                                       "NA"))))))))))))))))))))

#IGC 2 - many links forbidden

bbnj$webcast <- ifelse (bbnj$date == "2019-03-25" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1c/k1cxb3lnww?_gl=1*ovd6ce*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0ODM2OS4wLjAuMA..",
                        ifelse (bbnj$date == "2019-03-25" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k1t/k1tnyfvfah?_gl=1*c3jrnx*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0ODQyOS4wLjAuMA..",
                                ifelse (bbnj$date == "2019-03-26" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1e/k1eqz22qvq?_gl=1*ius9wl*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0ODk1Ny4wLjAuMA..",
                                        ifelse (bbnj$date == "2019-03-26" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://media.un.org/en/asset/k1x/k1xl0h35jz?_gl=1*c546z0*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0ODQ1OS4wLjAuMA..",
                                                ifelse (bbnj$date == "2019-03-27" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1g/k1g4hgsyc2?_gl=1*1o9bohz*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTAzOS4wLjAuMA..",
                                                        ifelse (bbnj$date == "2019-03-27" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k14/k14q5omcul?_gl=1*wxipmr*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTEyMy4wLjAuMA..",
                                                                ifelse (bbnj$date == "2019-03-28" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://media.un.org/en/asset/k1c/k1c48qbrgb?_gl=1*1q9j7pk*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTE3NC4wLjAuMA..",
                                                                        ifelse (bbnj$date == "2019-03-28" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://media.un.org/en/asset/k1b/k1bmsq0dze?_gl=1*jj25ni*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTI2OS4wLjAuMA..",
                                                                                ifelse (bbnj$date == "2019-03-29" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1s/k1s99xu12e?_gl=1*17qsp4p*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTMxNC4wLjAuMA..",
                                                                                        ifelse (bbnj$date == "2019-03-29" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k1w/k1w3qcei53?_gl=1*7c72v1*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTM2Ni4wLjAuMA..",
                                                                                                ifelse (bbnj$date == "2019-04-01" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1o/k1o2ged2zl?_gl=1*1y8sf0j*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTQyNC4wLjAuMA..",
                                                                                                        ifelse (bbnj$date == "2019-04-01" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"),  "https://edit.media.un.org/en/asset/k15/k15mklsjh0?_gl=1*2i9ht2*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTQ1Mi4wLjAuMA..",
                                                                                                                ifelse (bbnj$date == "2019-04-02" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1l/k1lnrmoe2c?_gl=1*o3uk6g*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTQ4OS4wLjAuMA..",
                                                                                                                        ifelse (bbnj$date == "2019-04-02" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k19/k190fy3qv0?_gl=1*szkmw3*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTUxOS4wLjAuMA..",
                                                                                                                                ifelse (bbnj$date == "2019-04-03" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1i/k1i9h3h2gf?_gl=1*9wu24r*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTU0OS4wLjAuMA..",
                                                                                                                                        ifelse (bbnj$date == "2019-04-03" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k1q/k1qitah4lc?_gl=1*47s897*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTU4My4wLjAuMA..",
                                                                                                                                                ifelse (bbnj$date == "2019-04-04" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1t/k1t27pm458?_gl=1*4tgpp1*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTYxNS4wLjAuMA..",
                                                                                                                                                        ifelse (bbnj$date == "2019-04-04" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k14/k14lmr4hj8?_gl=1*qk8jb*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTY0My4wLjAuMA..",
                                                                                                                                                                ifelse (bbnj$date == "2019-04-05" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1x/k1xs8mhjoc?_gl=1*1asdmwy*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTY1Ny4wLjAuMA..",
                                                                                                                                                                        ifelse (bbnj$date == "2019-04-05" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k15/k15j3c9c5m?_gl=1*vhjh16*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk0NjM2MC42LjEuMTY4Nzk0OTcwMi4wLjAuMA..", 
                                                                                                                                                                                bbnj$webcast))))))))))))))))))))


#IGC 3

bbnj$webcast <- ifelse (bbnj$date == "2019-08-19" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1j/k1j65zsts5?_gl=1*1yd5s96*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjAuMTY4Nzk1MTY5OC4wLjAuMA..",
                        ifelse (bbnj$date == "2019-08-19" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k16/k16cyo0wn9?_gl=1*1jk5pfs*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjAuMTY4Nzk1MTc0NS4wLjAuMA..",  
                                ifelse (bbnj$date == "2019-08-20" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k1v/k1vjnb4b2m?_gl=1*fx01ik*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjAuMTY4Nzk1MTgwMi4wLjAuMA..", 
                                        ifelse (bbnj$date == "2019-08-21" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1w/k1wavbr5ky?_gl=1*wop0xu*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjAuMTY4Nzk1MTg2OC4wLjAuMA..",
                                                ifelse (bbnj$date == "2019-08-22" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1z/k1zzffssq9?_gl=1*2fc8yi*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjAuMTY4Nzk1MTg5OC4wLjAuMA..",
                                                        ifelse (bbnj$date == "2019-08-23" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1q/k1qlq5ml4x?_gl=1*pxyv7u*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjAuMTY4Nzk1MTk2OS4wLjAuMA..",
                                                                ifelse (bbnj$date == "2019-08-26" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1v/k1v9qicumc?_gl=1*mm6chs*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjAzNS4wLjAuMA..",
                                                                        ifelse (bbnj$date == "2019-08-27" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://media.un.org/en/asset/k1s/k1s3wto2vo?_gl=1*ifwdlu*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjA2My4wLjAuMA..",
                                                                                ifelse (bbnj$date == "2019-08-28" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://media.un.org/en/asset/k16/k16r90i5lw?_gl=1*pb5gq1*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjA5MS4wLjAuMA..",
                                                                                        ifelse (bbnj$date == "2019-08-28" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"),  "https://media.un.org/en/asset/k1h/k1h912u0pk?_gl=1*1key600*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjEyMi4wLjAuMA..",
                                                                                                ifelse (bbnj$date == "2019-08-29" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://edit.media.un.org/en/asset/k1s/k1sz6jio53?_gl=1*16iven9*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjE5Ny4wLjAuMA..",  
                                                                                                        ifelse (bbnj$date == "2019-08-29" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://edit.media.un.org/en/asset/k1a/k1a7tdo3x9?_gl=1*2v8ozf*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjIwNS4wLjAuMA..",
                                                                                                                ifelse (bbnj$date == "2019-08-30" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://media.un.org/en/asset/k11/k11xlhw3li?_gl=1*6frr0k*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjI1Ny4wLjAuMA..", 
                                                                                                                        ifelse (bbnj$date == "2019-08-30" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://media.un.org/en/asset/k18/k18sfghmdt?_gl=1*1bg0b4a*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjI2Ny4wLjAuMA..",
                                                                                                                                bbnj$webcast))))))))))))))



#IGC 4 - neue Syntax
bbnj$webcast <- ifelse (bbnj$date == "2022-03-07" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1c/k1cz96pgf6?_gl=1*1n2yhu8*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjM3Ni4wLjAuMA..",
                        ifelse (bbnj$date == "2022-03-22" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1o/k1o3iae61f?_gl=1*chm34u*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjQ3NS4wLjAuMA.. ; https://media.un.org/en/asset/k1e/k1en6i0w0y?_gl=1*16xbsta*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjQ4Ni4wLjAuMA..", 
                                bbnj$webcast))       


#IGC 5 and following
bbnj$webcast <- ifelse (bbnj$date == "2022-08-15" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1p/k1pj5jzdzr?_gl=1*i6m9lc*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjU3MC4wLjAuMA..",
                        ifelse (bbnj$date == "2022-08-17" & bbnj$negotiation_format == "plenary",  "https://media.un.org/en/asset/k16/k166xap7q4?_gl=1*66bpft*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjYwMi4wLjAuMA..",
                                ifelse (bbnj$date == "2022-08-19" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k17/k178zqgzsp?_gl=1*o725nm*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MjkzNi4wLjAuMA..",
                                        ifelse (bbnj$date == "2022-08-23" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1o/k1osph3qsa?_gl=1*4j6zlc*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1Mjk4NC4wLjAuMA..",
                                                ifelse (bbnj$date == "2022-08-27" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1p/k1pu1nlyn8?_gl=1*iz3e74*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzAxMy4wLjAuMA..",
                                                        ifelse (bbnj$date == "2023-02-20" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1d/k1d3z5p128?_gl=1*1hb8tom*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzEyOS4wLjAuMA..",
                                                                ifelse (bbnj$date == "2023-02-22" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1u/k1upjhvglq?_gl=1*s4w0r8*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzE1MC4wLjAuMA..",
                                                                        ifelse (bbnj$date == "2023-02-23" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1n/k1np6z4i0c?_gl=1*4ekgqm*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzE4Ni4wLjAuMA..",
                                                                                ifelse (bbnj$date == "2023-02-24" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1b/k1bd5e0htu?_gl=1*n2iylx*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzI0OS4wLjAuMA..",
                                                                                        ifelse (bbnj$date == "2023-02-27" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1b/k1bd5e0htu?_gl=1*h1haeg*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzI4OC4wLjAuMA..",
                                                                                                ifelse (bbnj$date == "2023-02-28" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k11/k11uv3sh3f?_gl=1*ssrfcp*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzMxOC4wLjAuMA..",
                                                                                                        ifelse (bbnj$date == "2023-03-01" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k11/k112p0e47q?_gl=1*1j2efrp*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzM1NC4wLjAuMA..",
                                                                                                                ifelse (bbnj$date == "2023-03-02" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1d/k1dj02rwa3?_gl=1*dmv2ki*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzM5OC4wLjAuMA..",
                                                                                                                        ifelse (bbnj$date == "2023-03-03" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1e/k1e3cfuxiy?_gl=1*hbm9zd*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzQyOC4wLjAuMA..",
                                                                                                                                ifelse (bbnj$date == "2023-03-04" & bbnj$negotiation_format == "plenary", "https://media.un.org/en/asset/k1y/k1ywhtfciw?_gl=1*1xvxo52*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzQ0Ni4wLjAuMA..",
                                                                                                                                        bbnj$webcast)))))))))))))))


#IGC 5.3
bbnj$webcast <- ifelse (bbnj$date == "2023-06-19" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://media.un.org/en/asset/k12/k12gmlslmb?_gl=1*d5kchr*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzU3NC4wLjAuMA..",
                        ifelse (bbnj$date == "2023-06-19" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://media.un.org/en/asset/k1o/k1ooiq1xi1?_gl=1*pe8k8*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzYyMS4wLjAuMA..",
                                ifelse (bbnj$date == "2023-06-20" & (bbnj$time >= "10:00:00" & bbnj$time <= "13:00:00"), "https://media.un.org/en/asset/k12/k12gmlslmb?_gl=1*1bzc1px*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzYzNy4wLjAuMA..",
                                        ifelse (bbnj$date == "2023-06-20" & (bbnj$time >= "15:00:00" & bbnj$time <= "18:00:00"), "https://media.un.org/en/asset/k1n/k1n4255qyn?_gl=1*xyc1xr*_ga*NzU2NjE4OTU2LjE2NzU3NjYxMTM.*_ga_TK9BQL5X7Z*MTY4Nzk1MTY5Ni43LjEuMTY4Nzk1MzY0OC4wLjAuMA..", 
                                                bbnj$webcast))))



## Statements for IGC 2

bbnj$actor <- str_to_title(bbnj$actor)

bbnj$statement_link <- ifelse (bbnj$date == "2019-04-01" & (bbnj$actor == "Australia" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/australia2-1-april-1612-1614.pdf",
                               ifelse(bbnj$date == "2019-04-03" & (bbnj$actor == "Australia" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/australia2-3-april-1733-1739pm.pdf",
                                      ifelse(bbnj$date == "2019-03-29" & (bbnj$actor == "Australia" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/australia2-42-29-march-2019-1032-1037.pdf",
                                             ifelse(bbnj$date == "2019-03-27" & (bbnj$actor == "Australia" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/australia2-431-27-march-2019-1621-1625.pdf",
                                                    ifelse(bbnj$date == "2019-03-28" & (bbnj$actor == "Australia" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/australia2-intervention-for-upload-abmts-432-28-march-2019-1516-1525.pdf",
                                                           ifelse(bbnj$date == "2019-03-28" & (bbnj$actor == "Bangladesh" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/bangladesh2-4-april-pm.pdf",
                                                                  ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Chile" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/chile2_spain.pdf",
                                                                         ifelse(bbnj$date == "2019-04-04" & (bbnj$actor == "Ecuador" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/ecuador2_4-april.pdf",
                                                                                ifelse(bbnj$date == "2019-04-05" & (bbnj$actor == "Ecuador" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/ecuador2-5-april-pm.pdf",
                                                                                       ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "EU" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/eu2-25-march-.pdf",
                                                                                              ifelse(bbnj$date == "2019-03-27" & (bbnj$actor == "EU" & bbnj$package == 2),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/eu2-25-march-.pdf",
                                                                                                     ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Fiji" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fiji2-_-psids.pdf",
                                                                                                            ifelse(bbnj$date == "2019-04-05" & (bbnj$actor == "Fiji" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fiji2-psids-final-5-april.pdf",
                                                                                                                   ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Holy See" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/holy-see2.pdf",
                                                                                                                          ifelse(bbnj$date == "2019-04-02" & (bbnj$actor == "Iceland" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/iceland2-04-02_am.pdf",
                                                                                                                                 ifelse(bbnj$date == "2019-03-27" & (bbnj$actor == "Iceland" & bbnj$package == 1), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/iceland2-statement-on-mgrs-part-30-32-27-march-2019.pdf",
                                                                                                                                        NA))))))))))))))))
bbnj$statement_link <- ifelse (bbnj$date == "2019-03-27" & (bbnj$actor == "Japan" & bbnj$package == 1), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/japan2-27-march.pdf",
                               ifelse(bbnj$date == "2019-03-29" & (bbnj$actor == "Japan" & bbnj$package == 2),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/japan2-29.pdf",
                                      ifelse(bbnj$date == "2019-04-05" & (bbnj$actor == "Japan" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/japan2-5-april-am.pdf",
                                             ifelse(bbnj$date == "2019-04-05" & (bbnj$actor == "Mexico" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/mexico2-lalm.pdf",
                                                    ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Micronesia" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/mexico2-lalm.pdf",
                                                           ifelse(bbnj$date == "2019-04-01" & (bbnj$actor == "Micronesia" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/micronesia2-april-1-at-12-41pm.pdf , https://www.un.org/bbnj/sites/www.un.org.bbnj/files/micronesia2-eias-54-april-1_am.pdf",
                                                                  ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Morocco" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/morocco2.pdf",   
                                                                         ifelse(bbnj$date == "2019-04-05" & (bbnj$actor == "New Zealand" & bbnj$package == 5),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new-zealand2_5-april-am.pdf",
                                                                                ifelse(bbnj$date == "2019-04-03" & (bbnj$actor == "New Zealand" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new-zealand2-3-april-am_1.pdf",
                                                                                       ifelse(bbnj$date == "2019-04-04" & (bbnj$actor == "New Zealand" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new-zealand2-3-april-am.pdf",
                                                                                              ifelse(bbnj$date == "2019-04-04" & (bbnj$actor == "New Zealand" & bbnj$package == 5),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new-zealand2-04-02_pm.pdf",
                                                                                                     ifelse(bbnj$date == "2019-04-01" & (bbnj$actor == "New Zealand" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new-zealand2-4-april_2nd-am.pdf",
                                                                                                            ifelse(bbnj$date == "2019-03-29" & (bbnj$actor == "New Zealand" & bbnj$package == 1), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new-zealand2-intervention-abmts-44_45_41_definitions-3-29.pdf",
                                                                                                                   ifelse(bbnj$date == "2019-03-27" & (bbnj$actor == "New Zealand" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/palestine2.pdf",
                                                                                                                          ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Palestine" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/palestine2.pdf",
                                                                                                                                 ifelse(bbnj$date == "2019-04-05" & (bbnj$actor == "Palestine" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/palestine2-5-april-am.pdf",
                                                                                                                                        ifelse((bbnj$date == "2019-03-25" & bbnj$actor == "Palestine" & bbnj$package == 1)
                                                                                                                                               | (bbnj$date =="2019-03-26" & bbnj$actor == "Palestine" & bbnj$package == 1)
                                                                                                                                               | (bbnj$date == "2019-03-27" & bbnj$actor == "Palestine" & bbnj$package == 1),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/palestine2-on-behalf-of-g77-and-china-bbnj-igc2-agenda-item-7-intervention-on-mgr-25-27-march-2019-.pdf",
                                                                                                                                               ifelse((bbnj$date == "2019-03-27" & bbnj$actor == "Palestine" & bbnj$package == 2)
                                                                                                                                                      | (bbnj$date =="2019-03-28" & bbnj$actor == "Palestine" & bbnj$package == 2)
                                                                                                                                                      | (bbnj$date == "2019-03-29" & bbnj$actor == "Palestine" & bbnj$package == 2) , "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/palestine2-on-behalf-of-g77-and-china-intervention-bbnj-igc2-agenda-item-7-abmtmpa-27-29-march-fuad-bateh.pdf",
                                                                                                                                                      bbnj$statement_link))))))))))))))))))


bbnj$statement_link <- ifelse (bbnj$date == "2019-03-25" & (bbnj$actor == "Paraguay" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/paraguay2.pdf",
                               ifelse(bbnj$date == "2019-04-02" & (bbnj$actor == "Peru" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/peru2-2-april.pdf",
                                      ifelse(bbnj$date == "2019-03-28" & (bbnj$actor == "Philippines" & bbnj$package == 2),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/philippines2.pdf",
                                             ifelse(bbnj$date == "2019-04-01" & (bbnj$actor == "Philippines" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/philippines2-04-01_am.pdf",
                                                    ifelse(bbnj$date == "2019-04-02" & (bbnj$actor == "Philippines" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/philippines2-04-02_1139am.pdf",
                                                           ifelse(bbnj$date == "2019-04-03" & (bbnj$actor == "Philippines" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/philippines2-04-03_pm.pdf",
                                                                  ifelse(bbnj$date == "2019-04-04" & (bbnj$actor == "Philippines" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/philippines2-4-april-pm.pdf",
                                                                         ifelse(bbnj$date == "2019-04-04" & (bbnj$actor == "Senegal" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/senegal2-4-april.pdf",
                                                                                ifelse(bbnj$date == "2019-03-27" & (bbnj$actor == "Senegal" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/senegal2-27-march-pm.pdf",
                                                                                       ifelse(bbnj$date == "2019-03-28" & (bbnj$actor == "Seychelles" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/seychelles2-28.pdf",
                                                                                              ifelse(bbnj$date == "2019-04-04" & (bbnj$actor == "Singapore" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/singapores2-intervention-on-clearing-house-mechanism.pdf",
                                                                                                     ifelse(bbnj$date == "2019-04-02" & (bbnj$actor == "Singapore" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/singapores2-intervention-on-eias-51-and-52-am.pdf",
                                                                                                            ifelse(bbnj$date == "2019-04-03" & (bbnj$actor == "Singapore" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/singapores2-intervention-on-institutional-arrangements.pdf",
                                                                                                                   ifelse(bbnj$date == "2019-03-27" & (bbnj$actor == "Singapore" & bbnj$package == 1), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/singapores2-intervention-on-mgr-3-1-.pdf",
                                                                                                                          ifelse(bbnj$date == "2019-04-02" & (bbnj$actor == "Solomon Islands" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/solomon-islands2-psids-04-02_am.pdf",
                                                                                                                                 ifelse(bbnj$date == "2019-04-01" & (bbnj$actor == "Sri Lanka" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/sri-lanka2-04-01_1202pm.pdf",
                                                                                                                                        ifelse(bbnj$date == "2019-03-25" & (bbnj$actor == "Sudan" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/sudan2-25-march.pdf",
                                                                                                                                               ifelse(bbnj$date == "2019-04-03" & (bbnj$actor == "Tuvalu" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/tuvalu2-psids-3-april.pdf",
                                                                                                                                                      bbnj$statement_link))))))))))))))))))
## NGO/IGO statements in IGC 2
bbnj$statement_link <- ifelse (bbnj$date == "2019-03-27" & (bbnj$actor == "dosi" & bbnj$package == 1),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/dosi2_intervention3mgr31scopeaccess.pdf",
                               ifelse (bbnj$date == "2019-03-29" & (bbnj$actor == "dosi" & bbnj$package == 2),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/dosi2-29-march.pdf",
                                       ifelse (bbnj$date == "2019-04-02" & (bbnj$actor == "fao" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fao2-04-02_pm.pdf",
                                               ifelse (bbnj$date == "2019-04-03" & (bbnj$actor == "hsa" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/hsa2-04-03-pm.pdf", 
                                                       ifelse (bbnj$date == "2019-04-05" & (bbnj$actor == "hsa" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/hsa2-5-april-pm.pdf",
                                                               ifelse (bbnj$date == "2019-03-25" & (bbnj$actor == "icel" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icel2-mgrs-25-march-2019-general-exchange-of-views.pdf",
                                                                       ifelse (bbnj$date == "2019-03-26" & (bbnj$actor == "icel" & bbnj$package == 1), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icel2-26-march.pdf",
                                                                               ifelse (bbnj$date == "2019-03-27" & (bbnj$actor == "icel" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icel2-abmts-27-march-2019-abmt-identification-431-.pdf",
                                                                                       ifelse (bbnj$date == "2019-04-03" & (bbnj$actor == "icel" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icel2-3-april_am.pdf",
                                                                                               ifelse (bbnj$date == "2019-04-05" & (bbnj$actor == "icel" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icel2-5-april-am.pdf",
                                                                                                       ifelse (bbnj$date == "2019-04-05" & (bbnj$actor == "icpc" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icpc2-5-april-am.pdf",
                                                                                                               ifelse (bbnj$date == "2019-04-03" & (bbnj$actor == "icpc" & bbnj$package == 5),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icpc2-4-3_pm.pdf",
                                                                                                                       ifelse (bbnj$date == "2019-04-01" & (bbnj$actor == "icpc" & bbnj$package == 3),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icpc2-intervention-on-section-55-1april2019-.pdf",
                                                                                                                               ifelse (bbnj$date == "2019-03-25" & (bbnj$actor == "isa" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/international-seabed-authority2_bbnj-igcii_agenda-item-5.pdf",
                                                                                                                                       ifelse (bbnj$date == "2019-04-02" & (bbnj$actor == "unesco" & bbnj$package == 4), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/ioc2-04-02_pm.pdf",
                                                                                                                                               ifelse (bbnj$date == "2019-03-26" & (bbnj$actor == "iucn" & bbnj$package == 1), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/iucn2-26-march.pdf",
                                                                                                                                                       ifelse (bbnj$date == "2019-04-03" & (bbnj$actor == "npfc" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/npfc2-3-april-pm.pdf",
                                                                                                                                                               ifelse (bbnj$date == "2019-04-04" & (bbnj$actor == "ospar" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/ospar2-4-april.pdf",
                                                                                                                                                                       ifelse (bbnj$date == "2019-03-27" & (bbnj$actor == "pew" & bbnj$package == 2),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/pew2-charitable-trusts-on-behalf-of-hsa-intervention-on-abmt-431.pdf",
                                                                                                                                                                               ifelse (bbnj$date == "2019-04-03" & (bbnj$actor == "wwf" & bbnj$package == 5),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/wwf2-04-03_pm.pdf",
                                                                                                                                                                                       ifelse (bbnj$date == "2019-04-02" & (bbnj$actor == "wwf" & bbnj$package == 3),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/wwf2-53-eia-and-sea-04-02_am.pdf",
                                                                                                                                                                                               ifelse (bbnj$date == "2019-04-01" & (bbnj$actor == "wwf" & bbnj$package == 3),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/wwf2-57-sea-04-01_pm.pdf",
                                                                                                                                                                                                       bbnj$statement_link))))))))))))))))))))))
## Statements IGC 3
bbnj$statement_link <- ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Algeria" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/algeria3-obo-african-group.pdf",
                               ifelse (bbnj$date == "2019-08-30" & (bbnj$actor == "Barbados" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/barbados3-obo-caricom_1.pdf",
                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Barbados" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/barbados3-obo-caricom.pdf",
                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Belize" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/belize3-obo-aosis.pdf",
                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Colombia" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/colombia3-19-aug-2019.pdf",
                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Costa Rica" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/costa-rica3.pdf",
                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Ecuador" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/ecuador3.pdf",
                                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "EU" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/european-union3.pdf",
                                                                                       ifelse (bbnj$date == "2019-08-30" & (bbnj$actor == "EU" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/european-union3_1.pdf",
                                                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Iceland" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/iceland3.pdf",
                                                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Malawi" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/malawi3.pdf",
                                                                                                               ifelse (bbnj$date == "2019-08-30" & (bbnj$actor == "Micronesia" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/micronesia3_1.pdf",
                                                                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Micronesia" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/micronesia3.pdf",
                                                                                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Myanmar" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/myanmar3.pdf",
                                                                                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Palestine" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/palestine3-obo-g77-and-china.pdf",
                                                                                                                                               bbnj$statement_link)))))))))))))))

bbnj$statement_link <- ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Republic of Korea" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/rep-of-korea3.pdf",
                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Senegal" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/senegal3.pdf",
                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Singapore" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/singapore3.pdf",
                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Sudan" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/sudan3.pdf",
                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Thailand" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/thailand3.pdf",
                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Turkey" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/turkey3.pdf",
                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "Tuvalu" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/tuvalu3-obo-pif.pdf",
                                                                               ifelse (bbnj$date == "2019-08-30" & (bbnj$actor == "Tuvalu" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/tuvalu3-obo-pif_1.pdf",
                                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "hsa" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/high-seas-alliance3.pdf",
                                                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "icel" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icel3.pdf",
                                                                                                       ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "iucn" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/iucn3.pdf",
                                                                                                               ifelse (bbnj$date == "2019-08-19" & (bbnj$actor == "fiji" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/psids3.pdf",
                                                                                                                       bbnj$statement_link))))))))))))

## Statements IGC 4

bbnj$statement_link <- ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "icpc" & bbnj$package == 9), "http://www.un.org/bbnj/sites/www.un.org.bbnj/files/icpc_intervention_at_opening_session_of_igc-4.pdf",
                               ifelse (bbnj$date == "2022-03-07" & (bbnj$actor == "unep" & bbnj$package == 4), "http://www.un.org/bbnj/sites/www.un.org.bbnj/files/bbnj_igc4_agenda_item_6_cbtbt_by_unep_7_march_2022.pdf",
                                       ifelse (bbnj$date == "2022-03-08" & (bbnj$actor == "wwf" & bbnj$package == 4), "http://www.un.org/bbnj/sites/www.un.org.bbnj/files/bbnj_igc_4_agenda_item_6._informal_informals_on_8_march_2022_wwf.pdf",
                                               ifelse (bbnj$date == "2022-03-10" & (bbnj$actor == "wwf" & bbnj$package == 2),"http://www.un.org/bbnj/sites/www.un.org.bbnj/files/agenda_item_6_informal_informals_on_measures_abmt10_march_2022_wwf.pdf",
                                                       ifelse (bbnj$date == "2022-03-14" & (bbnj$actor == "wwf" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/agendaitem6informalinformalsoncrosscuttingissues14march2022wwfint.pdf , https://www.un.org/bbnj/sites/www.un.org.bbnj/files/agendaitem6informalinformalsoncrosscuttingissues14march2022wwfinternatio.pdf", 
                                                               ifelse (bbnj$date == "2022-03-14" & (bbnj$actor == "fao" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fao_-_agenda_item_6-_art_51.pdf",
                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "isa" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/bbnj_igc_4_agenda_item_5_general_exchange_of_views_150322_isa.pdf",
                                                                               ifelse (bbnj$date == "2022-03-16" & (bbnj$actor == "wwf" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/informal_informalsonenvironmentalimpactassessments16march_2022wwfinternatio.pdf",
                                                                                       ifelse (bbnj$date == "2022-03-10" & (bbnj$actor == "unep" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/unep_statement_abmt.pdf",
                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "icel" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/bbnj_igc4_agendat_item_5_icel_statement_16_mar_2022.pdf",
                                                                                                       ifelse (bbnj$date == "2022-03-15" & (bbnj$actor == "Nicaragua" & bbnj$package == 5), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/intervencion_de_nicaragua_15_de_marzo_2022.pdf",
                                                                                                               ifelse (bbnj$date == "2022-03-10" & (bbnj$actor == "neafc" & bbnj$package == 2),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/neafc_bbnj_igc4_agenda_item_6_informal_informals_on_area_based_management_tools.pdf",
                                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "oman" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/byn_sltn_mn_fy_khtm_jtmt_ldwr_lrb.pdf",
                                                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Colombia" | bbnj$actor == "El Salvador" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/rev_intervencion_colombia_y_el_salvador_-_debate_general_bbnj_-_clausula_de_salvaguardia_-_rev_col.pdf",    
                                                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Samoa" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/psids_closing_statement_igc4_bbnj_statement_final.pdf",
                                                                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Indonesia" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/indonesia_statement_closing_igc_4_bbnj_.pdf",
                                                                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "EU" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/bbnj_igc_4_closing_statement_18.3.2022.pdf",
                                                                                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Sierra Leone" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/sierra_leone_statement_on_behalf_of_the_au_at_the_fourth_session_of_the_international_legally_binding_instrument_under_the_un_convention_on_the_law_of_the_sea_-_18_march_2022.pdf",
                                                                                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Tonga" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/tongas_statement_at_the_closing_of_bbnj_igc4_2.pdf",
                                                                                                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "New Zealand" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/new_zealand_igc4_final_statement.pdf",
                                                                                                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Brazil" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/2022_03_18_mgrs_-_joint_statement.pdf",
                                                                                                                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Botswana" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/2aw0pf0caqrc_en.pdf",
                                                                                                                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Pakistan" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/hxbpxickm8rf_en.pdf",
                                                                                                                                                                                                               bbnj$statement_link)))))))))))))))))))))))
                                                                                                                                                                                                               
                               
bbnj$statement_link <- ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "IUCN" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/iucn_closing_statement_18_march_final.pdf",
                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Barbados" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/wdedzalbk4pw_en.pdf",
                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Fiji" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/i3qjmpadgby9_en.pdf",
                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Sri Lanka" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/muup0vtv6opt_en.pdf",
                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Dominican Republic" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/ehwhuqd8qlq4_es.pdf",
                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Bolivia" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/kkn6hjkfh8kk_es.pdf",
                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Thailand" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/wohtfcv5vj83_en.pdf",
                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Philippines" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/jsb9ap8sbnlw_en.pdf",
                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "Haiti" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/tqr9mss58uob_fr.pdf",
                                                                                               ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "UK" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/bbnj_igc4_uk_final_comments.pdf",
                                                                                                       ifelse (bbnj$date == "2022-03-18" & (bbnj$actor == "TUrkey" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/turkey_-_closing_statement_-_bbnj_igc_iv.pdf",
                                                                                                               bbnj$statement_link)))))))))))
## Statements IGC 5

bbnj$statement_link <- ifelse (bbnj$date == "2022-08-18" & (bbnj$actor == "Papua New Guinea" & bbnj$package == 3), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/eias_informal_informal_meeting_papua_new_guinea_statement.pdf",
                               ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "fao" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fao_-_agenda_item_5.pdf",
                                       ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "wwf" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/wwf_closing_statement_bbnj_igc5_26_aug_2022.pdf",
                                               ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "Micronesia" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fsm_statement_igc5_suspension_final.pdf",
                                                       ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "Costa Rica" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/igc5_costa_rica_plenary_statement_08.26.22.docx",
                                                               ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "Tonga" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/tonga_bbnj_statement_igc5_final.pdf",       
                                                                       ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "Nepal" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/nepal-_statement_during_general_exchange_of_views_on_bbnj_igc-v_on_26_aug_2022.pdf",
                                                                               ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "Liberia" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/liberias_concerns_and_decision_final_draft53816.pdf",
                                                                                       ifelse (bbnj$date == "2022-08-26" & (bbnj$actor == "Haiti" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/icg-5_intervention.pdf",
                                                                                               bbnj$statement_link)))))))))

## Statements IGC 6

bbnj$statement_link <- ifelse (bbnj$date == "2023-02-21" & (bbnj$actor == "gef"), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/gef_trust_fund_and_q_and_a_bbnj_02172023.pdf",
                               ifelse (bbnj$date == "2023-02-23" & (bbnj$actor == "fao" & bbnj$package == 9),  "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fao_-_agenda_item_5_0.pdf",
                                       ifelse (bbnj$date == "2023-02-23" & (bbnj$actor == "fao" & bbnj$package == 9),"https://www.un.org/bbnj/sites/www.un.org.bbnj/files/fao_-_agenda_item_5_0.pdf",
                                               ifelse (bbnj$date == "2023-02-27" & (bbnj$actor == "hsa"), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/hsa_igc5_statement.pdf",
                                                       ifelse (bbnj$date == "2023-02-27" & (bbnj$actor == "isa" & bbnj$package == 9), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/isa_statement-igc5_resumed_online_version.pdf",
                                                               ifelse (bbnj$date == "2023-03-03" & (bbnj$actor == "Palau" & bbnj$package == 2), "https://www.un.org/bbnj/sites/www.un.org.bbnj/files/psids_statement_day_10-plenary.pdf",
                                                                       bbnj$statement_link))))))
                                                                      
                                                                                       