# this code was written by Simon Fellinger 

bbnj <- mutate(bbnj, obo = ifelse(IGC == 1 & actor == "egypt", "g77+china",
                                  ifelse((IGC == 2 | IGC == 3 | IGC == 5) & actor == "palestine", "g77+china",
                                         ifelse((IGC == 4 | IGC == 5) & actor == "pakistan", "g77+china",
                                                ifelse(IGC == 6 & actor == "cuba", "g77+china",
                                                       ifelse((IGC == 2) & (package == 4) & actor == "india", "g77+china",
                                                              ifelse((IGC == 2) & (package == 3) & actor == "solomon islands", "g77+china",
                                                                     ifelse((IGC == 2) & (package == 3) & actor == "federated states of micronesia", "g77+china",
                                                                            ifelse((IGC == 2) & (package == 4) & actor == "algeria", "g77+china",
                                                                                   ifelse((IGC == 2) & (package == 4) & actor == "bahamas", "g77+china",
                                                                                          ifelse((IGC == 2) & (package == 5) & actor == "senegal", "g77+china",
                                                                                                 ifelse((IGC == 3) & (package == 1) & actor == "china", "g77+china",
                                                                                                        ifelse((IGC == 6) & (package == 4) & actor == "palestine", "g77+china",
                                                                                                               ifelse((IGC == "intersessional work") & (package == 4) & actor == "guyana", "g77+china",
                                                                                                                      ifelse((IGC == "intersessional work") & (package == 2) & actor == "pakistan", "g77+china",
                                                                                                                             ifelse((IGC == "intersessional work") & (package == 9) & actor == "cuba", "g77+china",
                                                                                                                                    ifelse((IGC == "onlinedialogues") & (package == 4) & actor == "guyana", "g77+china",
                                                                                                                                           ifelse((IGC == "onlinedialogues") & (package == 5) & actor == "colombia", "g77+china",
                                                                                                                                                  ifelse((IGC == "onlinedialogues") & (package == 3) & actor == "palestine", "g77+china",
                                                                                                                                                         bbnj$actor)))))))))))))))))))

bbnj$obo <- ifelse((bbnj$IGC == 1 ) & bbnj$actor == "maldives", "Aosis",                                            
                    ifelse((bbnj$IGC == 2) & bbnj$actor == "belize", "Aosis",
                           ifelse((bbnj$IGC == "intersessional work" |bbnj$IGC == "onlinedialogues") & bbnj$package == 1 & bbnj$actor == "belize", "Aosis",
                                  ifelse((bbnj$IGC == 3 ) & (bbnj$package == 9 | bbnj$package == 1) & bbnj$actor == "belize", "Aosis",
                                         ifelse((bbnj$IGC == 2 | bbnj$IGC == 3) & (bbnj$package == 4 | bbnj$package == 5) & bbnj$actor == "belize", "Aosis",
                                                ifelse((bbnj$IGC == 4) & (bbnj$package == 4) & bbnj$actor == "antigua and barbuda", "Aosis",
                                                       ifelse((bbnj$IGC == "intersessional work") & (bbnj$package == 4 |bbnj$package ==1) & bbnj$actor == "antigua and barbuda", "Aosis",
                                                              ifelse((bbnj$IGC == 5) & (bbnj$package == 4 | bbnj$package == 5 | bbnj$package == 9 | bbnj$package == 2) & bbnj$actor == "antigua and barbuda", "Aosis",
                                                                     ifelse((bbnj$IGC == 6) & (bbnj$package == 3) & bbnj$actor == "samoa", "Aosis",
                                                                            bbnj$obo)))))))))												


bbnj$obo <- ifelse((bbnj$IGC == 1 |bbnj$IGC == 2  | bbnj$IGC == 3) & bbnj$actor == "algeria", "African Group",
                   ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6 | bbnj$IGC == "onlinedialogues") & (bbnj$package == 4 | bbnj$package == 5) & bbnj$actor == "morocco", "African Group",
                          ifelse((bbnj$IGC == 6) & bbnj$package == 3 & bbnj$actor == "morocco", "African Group",
                                 ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC ==6) & (bbnj$package == 1 | bbnj$package == 9) & bbnj$actor == "sierra leone", "African Group",
                                        ifelse((bbnj$IGC == 4) & (bbnj$package == 3 | bbnj$package == 5 ) & bbnj$actor =="sierra leone", "African Group",
                                               ifelse((bbnj$IGC == "intersessional work" | bbnj$IGC == "onlinedialogues") & (bbnj$actor == "sierra leone"), "African Group",
                                                      ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & bbnj$package == 2 & bbnj$actor == "seychelles", "African Group",
                                                             ifelse((bbnj$IGC == 6) & bbnj$package == 3 & bbnj$actor == "seychelles", "African Group",
                                                                    ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6 | bbnj$IGC == "onlinedialogues") & bbnj$package == 5 & bbnj$actor == "south africa", "African Group",
                                                                           ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & bbnj$package == 3 & bbnj$actor == "mauritius", "African Group",
                                                                                  ifelse((bbnj$IGC == 2) & (bbnj$package == 9) & bbnj$actor == "sudan", "African Group",
                                                                                         ifelse((bbnj$IGC == 2) & (bbnj$package == 5) & bbnj$actor == "senegal", "African Group",
                                                                                                ifelse((bbnj$IGC == 3) & (bbnj$package == 3) & bbnj$actor == "sierra leone", "African Group",
                                                                                                       ifelse((bbnj$IGC == 5) & (bbnj$package == 9) & bbnj$actor == "namibia", "African Group",
                                                                                                              ifelse((bbnj$IGC == 6) & (bbnj$package == 9 | bbnj$package == 1) & bbnj$actor == "kenya", "African Group",
                                                                                                                     ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 4) & bbnj$actor == "algeria", "African Group",
                                                                                                                            bbnj$obo))))))))))))))))

bbnj$obo <- ifelse((bbnj$IGC == 1 ) & bbnj$actor == "bangladesh", "LDC",
                   ifelse((bbnj$IGC == 3 ) & bbnj$actor == "malawi", "LDC",
                          ifelse((bbnj$IGC == 1 | bbnj$IGC == 2 | bbnj$IGC == 3) & bbnj$actor == "paraguay", "Landlocked",
                                 bbnj$obo)))

bbnj$obo <- ifelse((bbnj$IGC == 1 ) & bbnj$package == 9 & bbnj$actor == "barbados", "Caricom",
                   ifelse((bbnj$IGC == 1 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & bbnj$package == 4 & bbnj$actor == "saint lucia", "Caricom",
                          ifelse((bbnj$IGC == 1 ) & bbnj$package == 1 & bbnj$actor == "saint lucia", "Caricom",
                                 ifelse((bbnj$IGC == 3) & (bbnj$package == 5) & bbnj$actor == "saint lucia", "Caricom",
                                        ifelse((bbnj$IGC == 1 ) & bbnj$package == 2 & bbnj$actor == "bahamas", "Caricom",
                                               ifelse((bbnj$IGC == 2 ) & bbnj$package == 4 & bbnj$actor == "bahamas", "Caricom", 
                                                      ifelse((bbnj$IGC == 3 ) & bbnj$package == 2 & bbnj$actor == "jamaica", "Caricom", 
                                                             ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 1) & bbnj$actor == "barbados", "Caricom",
                                                                    ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 2 | bbnj$package == 5) & bbnj$actor == "barbados", "Caricom",
                                                                           ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 |bbnj$IGC == 5 | bbnj$IGC == 6) & bbnj$package == 3 & bbnj$actor == "trinidad and tobago", "Caricom",
                                                                                  ifelse((bbnj$IGC == 2 | bbnj$IGC == 4 | bbnj$IGC == 5) & bbnj$package == 4 & bbnj$actor == "bahamas", "Caricom",
                                                                                         ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC ==5 | bbnj$IGC == 6) & bbnj$package == 5 & bbnj$actor == "jamaica", "Caricom",
                                                                                                ifelse((bbnj$IGC ==3 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 2) & bbnj$actor == "belize", "Caricom",
                                                                                                       ifelse((bbnj$IGC == 4 ) & bbnj$package == 4 & bbnj$actor == "jamaica", "Caricom", 
                                                                                                              ifelse((bbnj$IGC == 6 ) & bbnj$package == 3 & bbnj$actor == "jamaica", "Caricom", 
                                                                                                                     ifelse((bbnj$IGC == "intersessional work" ) & bbnj$actor == "barbados", "Caricom", 
                                                                                                                            ifelse((bbnj$IGC == "intersessional work" ) & bbnj$actor == "belize", "Caricom",
                                                                                                                                   ifelse((bbnj$IGC == "intersessional work" ) & bbnj$actor == "barbados", "Caricom", 
                                                                                                                                          ifelse((bbnj$IGC == "intersessional work" ) & bbnj$actor == "jamaica", "Caricom", 
                                                                                                                                                 ifelse((bbnj$IGC == "intersessional work" ) & bbnj$actor == "guyana", "Caricom", 
                                                                                                                                                        ifelse((bbnj$IGC == "intersessional work" ) & bbnj$actor == "bahamas", "Caricom", 
                                                                                                                                                               ifelse((bbnj$IGC == 2) & (bbnj$package == 9) & bbnj$actor == "belize", "Caricom",
                                                                                                                                                                      ifelse((bbnj$IGC == 2 | bbnj$IGC == 3) & (bbnj$package == 9) & bbnj$actor == "barbados", "Caricom",
                                                                                                                                                                             ifelse((bbnj$IGC == 3) & (bbnj$package == 4) & bbnj$actor == "tuvalu", "Caricom",
                                                                                                                                                                                    ifelse((bbnj$IGC == 3) & (bbnj$package == 3 | bbnj$package == 4) & bbnj$actor == "trinidad and tobago", "Caricom",
                                                                                                                                                                                           ifelse((bbnj$IGC == 4) & (bbnj$package == 1) & bbnj$actor == "jamaica", "Caricom",
                                                                                                                                                                                                  ifelse((bbnj$IGC == 5) & (bbnj$package == 3) & bbnj$actor == "belize", "Caricom",
                                                                                                                                                                                                         ifelse((bbnj$IGC == 5) & (bbnj$package == 3) & bbnj$actor == "samoa", "Caricom",
                                                                                                                                                                                                                ifelse((bbnj$IGC == 5) & (bbnj$package == 4) & bbnj$actor == "antigua and barbuda", "Caricom",
                                                                                                                                                                                                                       ifelse((bbnj$IGC == 5) & (bbnj$package == 9) & bbnj$actor == "barbados", "Caricom",
                                                                                                                                                                                                                              ifelse((bbnj$IGC == 6) & (bbnj$package == 9) & bbnj$actor == "jamaica", "Caricom",
                                                                                                                                                                                                                                     ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1) & bbnj$actor == "trinidad and tobago", "Caricom",
                                                                                                                                                                                                                                            bbnj$obo))))))))))))))))))))))))))))))))



bbnj$obo <- ifelse((bbnj$IGC == 1 ) & (bbnj$package == 9) & bbnj$actor == "palau", "Psids",
                   ifelse((bbnj$IGC == 1 ) & (bbnj$package == 2 | bbnj$package == 3) & bbnj$actor == "nauru", "Psids",
                          ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 5) & bbnj$actor == "nauru", "Psids",
                                 ifelse((bbnj$IGC == 5) & (bbnj$package == 1) & bbnj$actor == "nauru", "Psids",
                                        ifelse((bbnj$IGC == 6 | bbnj$IGC == "intersessional work") & (bbnj$package == 3) & bbnj$actor == "nauru", "Psids",
                                               ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == "intersessional work") & (bbnj$package == 1) & bbnj$actor == "fiji", "Psids",
                                                      ifelse((bbnj$IGC == 2) & (bbnj$package == 5) & bbnj$actor == "fiji", "Psids",
                                                             ifelse((bbnj$IGC == 3) & (bbnj$package == 9 | bbnj$package == 3) & bbnj$actor == "fiji", "Psids",
                                                                    ifelse((bbnj$IGC == 4) & (bbnj$package == 9 | bbnj$package == 5) & bbnj$actor == "fiji", "Psids",
                                                                           ifelse((bbnj$IGC == 2 | bbnj$IGC == 3) & (bbnj$package == 4) & bbnj$actor == "tuvalu", "Psids",
                                                                                  ifelse(( bbnj$IGC == 3) & (bbnj$package == 2 | bbnj$package == 9) & bbnj$actor == "tuvalu", "Psids",
                                                                                         ifelse((bbnj$IGC == 2 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 2) & bbnj$actor == "federated states of micronesia", "Psids",
                                                                                                ifelse((bbnj$IGC == 2) & (bbnj$package == 5) & bbnj$actor == " federated states of micronesia ", "Psids",
                                                                                                       ifelse((bbnj$IGC == 3 | bbnj$IGC == 5 |bbnj$IGC == 6) & (bbnj$package == 3) & bbnj$actor == "federated states of micronesia", "Psids",
                                                                                                              ifelse((bbnj$IGC == 6) & (bbnj$package == 4) & bbnj$actor == "palau", "Psids",
                                                                                                                     ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 6) & (bbnj$package == 3) & bbnj$actor == "solomon island", "Psids",
                                                                                                                            ifelse((bbnj$IGC == 3) & (bbnj$package == 5) & bbnj$actor == "solomon island", "Psids",
                                                                                                                                   ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 4) & bbnj$actor == "palau", "Psids",
                                                                                                                                          ifelse((bbnj$IGC == 6) & (bbnj$package == 3 | bbnj$package == 9) & bbnj$actor == "palau", "Psids",
                                                                                                                                                 ifelse((bbnj$IGC == 4 | bbnj$IGC ==5) & (bbnj$package == 3 | bbnj$package == 9 ) & bbnj$actor == "samoa", "Psids",
                                                                                                                                                        ifelse((bbnj$IGC ==5) & (bbnj$package == 5) & bbnj$actor == "samoa", "Psids",
                                                                                                                                                               ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 |bbnj$package == 2 | bbnj$package == 3 | bbnj$package ==4 | bbnj$package == 9) & bbnj$actor == "federated states of micronesia", "Psids",
                                                                                                                                                                      ifelse((bbnj$IGC == "onlinedialogues") & ( bbnj$package ==4 | bbnj$package == 5 |bbnj$package == 9) & bbnj$actor == "fiji", "Psids",
                                                                                                                                                                             ifelse((bbnj$IGC == "onlinedialogues") & bbnj$actor == "nauru", "Psids",
                                                                                                                                                                                    ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 3) & bbnj$actor == "samoa", "Psids",
                                                                                                                                                                                           ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1) & bbnj$actor == "solomon islands", "Psids",
                                                                                                                                                                                                  ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 | bbnj$package == 5 ) & bbnj$actor == "tuvalu", "Psids",
                                                                                                                                                                                                         bbnj$obo)))))))))))))))))))))))))))


bbnj$obo <- ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6 | bbnj$IGC == "intersessional work" | bbnj$IGC == "onlinedialogues") & (bbnj$package == 1) & (bbnj$actor == "brazil"), "Clam", 
                   ifelse((bbnj$IGC == 3) & (bbnj$package == 4) & bbnj$actor == "brazil", "Clam", 
                          ifelse((bbnj$IGC == 4) & (bbnj$package == 5) & bbnj$actor == "brazil", "Clam",
                                 ifelse((bbnj$IGC == 6 | bbnj$IGC == "onlinedialogues") & (bbnj$package == 2 | bbnj$package == 3) & bbnj$actor == "brazil", "Clam",
                                        ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 4) & bbnj$actor == "el salvador", "Clam",
                                               ifelse((bbnj$IGC == 2 | bbnj$IGC == 4 | bbnj$IGC == 5 |bbnj$IGC == 6) & (bbnj$package == 2) & bbnj$actor == "argentina", "Clam",
                                                      ifelse((bbnj$IGC == 6) & (bbnj$package == 3) & bbnj$actor == "argentinia", "Clam", 
                                                             ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 | bbnj$package == 2 | bbnj$package == 3 | bbnj$package == 4) & bbnj$actor == "argentinia", "Clam",
                                                                    ifelse((bbnj$IGC == 2 | bbnj$IGC == 3) & (bbnj$package == 3 |bbnj$package == 4) & bbnj$actor == "uruguay", "Clam",
                                                                           ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5) & (bbnj$package == 4) & bbnj$actor == "honduras", "Clam",
                                                                                  ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 | bbnj$package == 3 | bbnj$package == 5 ) & bbnj$actor == "honduras", "Clam",
                                                                                         ifelse((bbnj$IGC == 2 | bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 5) & bbnj$actor == "colombia", "Clam",
                                                                                                ifelse((bbnj$IGC == 4 | bbnj$IGC == "intersessional work" | bbnj$IGC == "onlinedialogues") & (bbnj$package == 1) & bbnj$actor == "colombia", "Clam",
                                                                                                       ifelse((bbnj$IGC == 6 | bbnj$IGC == "onlinedialogues") & (bbnj$package == 2 | bbnj$package == 3 | bbnj$package == 4 | bbnj$package == 5 | bbnj$package == 9) & bbnj$actor == "colombia", "Clam",
                                                                                                              ifelse((bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & bbnj$package == 5 & bbnj$actor == "mexico", "Clam",
                                                                                                                     ifelse((bbnj$IGC == 4) & (bbnj$package == 9) & bbnj$actor == "mexico", "Clam",
                                                                                                                            ifelse((bbnj$IGC == 6) & (bbnj$package == 3) & bbnj$actor == "mexico", "Clam",
                                                                                                                                   ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 |bbnj$package == 2 | bbnj$package == 3 | bbnj$package == 4 | bbnj$package == 5 ) & bbnj$actor == "mexico", "Clam",
                                                                                                                                          ifelse((bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 ) & bbnj$package == 4 & bbnj$actor == "el salvador", "Clam",
                                                                                                                                                 ifelse((bbnj$IGC == 5) & (bbnj$package == 2) & bbnj$actor == "el salvador", "Clam",
                                                                                                                                                        ifelse((bbnj$IGC == 6) & (bbnj$package == 5) & bbnj$actor == "el salvador", "Clam",
                                                                                                                                                               ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 | bbnj$package == 4) & bbnj$actor == "el salvador", "Clam",
                                                                                                                                                                      ifelse((bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == "intersessional work" | bbnj$IGC == "onlinedialogues") & (bbnj$package == 3) & bbnj$actor == "guatemala", "Clam",  
                                                                                                                                                                             ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 4 | bbnj$package == 5 | bbnj$package == 9) & bbnj$actor == "guatemala", "Clam",   
                                                                                                                                                                                    ifelse((bbnj$IGC == 3 | bbnj$IGC == 4 | bbnj$IGC == 5) & (bbnj$package == 2 |bbnj$package == 3 | bbnj$package == 5) & bbnj$actor == "costa rica", "Clam",
                                                                                                                                                                                           ifelse((bbnj$IGC == 4 | bbnj$IGC == 5 | bbnj$IGC == 6) & (bbnj$package == 5) & bbnj$actor == "ecuador", "Clam", 
                                                                                                                                                                                                  ifelse((bbnj$IGC == "onlinedialogues") & (bbnj$package == 1 | bbnj$package == 2 | bbnj$package == 5) & bbnj$actor == "ecuador", "Clam",
                                                                                                                                                                                                         ifelse((bbnj$IGC == 5) & (bbnj$package == 2 | bbnj$package == 5) & bbnj$actor == "chile", "Clam",
                                                                                                                                                                                                                ifelse((bbnj$IGC == 5) & (bbnj$package == 3) & bbnj$actor == "peru", "Clam",
                                                                                                                                                                                                                       ifelse((bbnj$IGC == 5) & (bbnj$package == 5) & bbnj$actor == "jamaica", "Clam",
                                                                                                                                                                                                                              ifelse((bbnj$IGC == 5) & (bbnj$package == 9) & (bbnj$actor == "mexico" |bbnj$actor == "costa rica" | bbnj$actor == "ecuador"), "Clam",
                                                                                                                                                                                                                                     ifelse((bbnj$IGC == 6) & (bbnj$package == 9 | bbnj$package == 1 ) & bbnj$actor == "colombia", "Clam",
                                                                                                                                                                                                                                            bbnj$obo))))))))))))))))))))))))))))))))
bbnj$obo <- str_to_lower(bbnj$obo)



table(bbnj$obo)