###################### pro_contra variable

bbnj$pro_contra[bbnj$pro_contra == "yes"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "ys"] <- "pro"

bbnj$pro_contra[bbnj$pro_contra == "no"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "delete"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "con"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "maybe"] <- "neutral"
bbnj$pro_contra[bbnj$pro_contra == "0"] <- "neutral"
bbnj$pro_contra[bbnj$pro_contra == "??"] <- "?"
bbnj$pro_contra[bbnj$pro_contra == "???xxx"] <- "?"
bbnj$pro_contra[bbnj$pro_contra == "cion"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "cn"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "con/flexibleible"] <- "contra/flexible"
bbnj$pro_contra[bbnj$pro_contra == "con/flexible"] <- "contra/flexible"
bbnj$pro_contra[bbnj$pro_contra == "con/pro"] <- "contra/pro"
bbnj$pro_contra[bbnj$pro_contra == "flex"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "flexibleble"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "flexibleibel"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "flexibleible"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "flexibleile"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "flexiblel"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "fley"] <- "flexible"
bbnj$pro_contra[bbnj$pro_contra == "fpro"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "po"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "por"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "ppro"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "proi"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "opro"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "prp"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "pref"] <- "preference"
bbnj$pro_contra[bbnj$pro_contra == "pro or con"] <- "pro or contra"
bbnj$pro_contra[bbnj$pro_contra == "pro/fle/flexible"] <- "pro/flexible"
bbnj$pro_contra[bbnj$pro_contra == "prr"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "pto"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "rather con"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "rpo"] <- "pro"
bbnj$pro_contra[bbnj$pro_contra == "xon"] <- "contra"
bbnj$pro_contra[bbnj$pro_contra == "xx"] <- "XXX"
bbnj$pro_contra[bbnj$pro_contra == "XX"] <- "XXX"
bbnj$pro_contra[bbnj$pro_contra == "maby"] <- "maybe"