### word correction
badwords.corpus <- c("teared", "TK", "peooooople", "clan", "science-based", "paletine", "opeions",
                     "heriatge", "aprties", "negotions", "pricniple", "intergate", "instument", "particualr",
                     "countrities", "florr", "shairng", "intrnational", "volontary", "coomon",
                     "heriatge", "CBBD", "repition", "oh", "japoanese", "hritage",
                     "bahelf", "obo", "on behalf od", "isaland", "caribean", "ngos", "sg",
                     "King & Spalding", "mauritious", "hihglight", "picis","chanes",
                     "enviornment", "jurisditional", "stats", "broadenin", "differentite", "diffrent", "eploratory",
                     "actiities", "acidificaiton", "trasnparency", "isses", "bioduversity", "unsustaible", "accidifcation",
                     "elemetns", "cliamte", "modifiyng", "alge", "legeal", "releavnt", "patchworkd", "systeam",
                     "agreeement", "mesaures", "mouvements", "notificisiton", "suficently", "advanceents",
                     "descriotions", "accoustic", "refernece", "panned", "hamr", "eveniotnment","treshhold", "trshhold",
                     "soveriegn", "archipelaig", "sontinental", "coean", "transbounrady", "accoutn", "adjecient", "impats", 
                     "instrumnt", "impct", "metnioned", "baus", "anothet", "souvereighn", 
                     "wibed", "trandboundary", "algaeria", "scinetific", "sction", "evalluate", "wehre", "avialbale",
                     "scinece", "relfect", "ipccc", "ocnsitent", "traditinal", "crtieria", "ebsta", "soverreign",
                     "assessmen", "defitnion", "defition", "defintions", "cartegena", "dorsee", "tribunal for the law of the sea",
                     "cooepration", "awnj", "oceanic comminssin", "assesssmentt", "assessmenttt", "noa", "angoya", "conservaiton",
                     "reserach", "workding", "precautiaonary", "exmaple", "ioc_unesco", "guidilnes","cuntries", "scracth", "researhcers", "technoloyg",
                     "technoligy", "technooyg", "braodly", "involunary", "aprotpotae", "aextending", "foam", "organsaion", "exising",
                     "clearing house", "celaring", "hav", "specifis", "insturment", "collet", "informaiton", "follwoing",
                     "informatio", "implementaiton", "desirbaility", "isntrumente", "supprot", "regaret", "aiuthorty", "equlity", "occirs",
                     "hgihest", "reocgnition", "decision making", "rfmos", "regional fisheries management organizations", "undermaine", "haveee",
                     "mechnaisms", "emasures", "toerh", "gurther", "convetion", "tofer",
                     ' ist ', 'havee', 'consultaiton', 'identificaiotn', ' i ', 'informationn ', 'assessmentt', 'assessmentts ', 'yb ', ' ad ', 
                     'cimmoitted ', 'dumpling', 'atalntic', 'comrpises ', 'madnate ', 'memorandom ', 'multialteral ', 'establihsed ', 'arrangemnt',
                     'possibe', 'loctaed', 'wiht ', 'reccommendations', 'consevation', 'secreatiat', 'iten', 'organisaitonal', 'compsoition', 'memberes', 
                     'presdient', 'foloowing','european',
                     'waht' ,'havee' ,'menas' ,' ot ' ,'respectt' ,'informationn' ,'sharinf' ,'taks' ,'eprovisiosn' ,'enahnce' ,'mehcanism' ,' si ',
                     'coutnries' ,'agreemnets' ,'communiting' ,'reguluating' ,'approprite' ,'curretn','translatin','amke','difficutl','volutarny',
                     'geentic','theri','haveing','cann','doe','snto','ius','bean',' adn ','htese','eissue','thos',' sin ',' din ',
                     'informationn', 'organsiation', 'enure', 'waht', 'theis', 'contex', 'avaible', 'geoups', 'peacful',
                     'shuld', 'waht', 'enahnce',
                     'assessmentts','wihtout','htis','viewes','volunatrybeenfit','acces','suport','benefir','entitiy','juridsection',
                     'exploiation','govrment','waht','theis','contex','availble','refelct','genration','conservtion','supoort','exerise',
                     'volunatriyl','objectuve','havee',' ist ','assessmentt','knowlegde','fleyible','susbtance','negitions',
                     'decions','basee','organsiaiton','havee','promotr','capacty','cooerationa','effectie','procesudres','desirbale','heere.',
                     'committet','canu','objectuve','woth','fleyible', 
                     'assessmentt', 'relationshio<U+FFFD>s tp tofer', 'genral', 'principels', 'mechsnism', 'relatio to tofer', 'ters', 'arrnagements',
                     'nto', 'lits', 'deciison', 'cbtt', 'coorination', 'ters', 'temrs', ' proviison ', 'itsu', 'funing', 
                     'tk', "develeopment", "deicsoins", " sec ", "ooperationalised", "fwlible", "textul", "liek",
                     "consenssus", "finl", "anyhting", "tgether", "tranparent", "proviisons", "definitoin", "tred", "faclitation", "holistic",
                     " sust ", "oncpet", "optoin", "soecific", "chnages", " camlr ", "nhabitants", "ditsingush", "definioof", "importnat",
                     "inlcude", "suggeitson", "conservaito", "conservationa", " nd ", "adoto", "isngapore", "thnaks", "braoder", "includeing",
                     "withsmal", "breidge", "drfating", "competnet", "ccoperation:.", "inckude", "africna", "intenrationla", "inot", "consultatino on",
                     "consultatino", "monitoing", "responisbility", "monitring", "exitisng", "responisbilities", "objecives", "objecties",
                     "poissbility", "rleevnt", "constency", "prposed", "acitivites", "msut", "condier", "dleegates", "birng",
                     "cnsult", "memebrs", "reserch", "exitsing", "doess", "estalishing", "coperatoin", " mech ", "anoter", "interfeere", "manate",
                     "isze", "felyible", "plcement", "cnisder", "acience", "avaiablel", "incluing", "cietific", "infonite", "staekhodlers", "stakeodlers",
                     "scirntific", "ebsas-", "dicsuison", "oulinign", "sesison", "diffeentiate", "approaritate", " faor ", "xitsing", "proviisonal", "posisbility",
                     "mechainsm", "trasnfer", "insitutional", " tresholds ", "managemnt", "builing", " as a whole ", "analyiss", " tk " , " accessss ", " accesss ",
                     "clering house mechanism", " tk", " cbtt", " word bank",
                     "establish>",  "estbalish", "estblaih", "estblish",
                     "establishment>", "estbalishment", "estbalishemtn", "estbalihsment", "estblaihsment", "estbalishment", "estbalishemtn", "estbalihsmentv", "estbalisment", "estbalishemnt", "estbalihsment",
                     "established>", "estbalished", "estblished", "estbalihed", "estbalihed", "estblishe", "estbaished", "estbalihsed", "estbalied", "estbalished", "estbalihsed", "estblishes", 
                     "establishing>", "estbalishing", "estbalihisng", "estbaishing", "conisder", "poissble", "preisdent", "biodiveritsy", "baiss",
                     "discuissons", "discuisson", " tri ", "plastix", "egotiating", "avialbel", "avialbel", "inedigesou", "scientifi", " knoldge ", " ismilar ", " borad ", "ditiscintion", " lcate ", "demans", " gnetic ",
                     "defintion", "ditisnct", "esnure", "paragraofs", "instrinsci", "culturl", "agreemetn", "exiisng", "preferencess", "negoitations", "negoitation ", "sueful", "intermsessional", "effetive",
                     "memebr states", "worlshops", " gavor ", "maissve", " mayn ", "biodiveritsy", " canot ", "consulation", "incluison", " whle ", "frsmework",
                     "sufficent", "sanctino", "envirnemtnal", "imapct", "poissble", "discuisson", "preisdents",
                     "isncere", "collecitve", "holitically", " poeple ", " progres ", "ruissan", " bining ", " fulfull ", " polticla ", " riased ", 
                     " underine ", " isxth ", " oppoitison ", " imited ", " isx ", "souverainty", " connectoin ", "civilsociety", " concrns ", " attnetino ", "nnnegotiating",
                     "aisapacific", "aggreisson", "consideratoins", " stpe ", " venezuea ", " affiars ", " agreissng ", " agreissve ", " aissdt ", " andcommercialisation ",
                     " aprticipated ", " approapite ", " athmposher ", " attemtp ", " backrgound ", " balnaces ", " beenn "," belonsecretariats ", " benefi ", 
                     " biologits ", " brders ", "burocrotised", "capabitlities", " copw ", " ith ", " scintific ", "ditisnguished", "scientificcccc", " para ",
                     "contextttttualize", "excurisons", "compoitison", "ruissand", "paragrpahs", "ditisnguished", "expreissons", "focuisng", "contexttttttts", 
                     "microneisa", "importanc eto", " reently", "contexttttt"," yu ", " cnanot ", " disucisson ", " shoud ", " scientificccc ", "evidenece", "iscneitfic", 
                     " consideratoin ", " conyl ", " comunties ", " possble ", " negitve ", " impat ", " poitisve ", " anegtive ", " pictute ", " scientificccc ", "scientificcc", "supposedto",
                     "postoned", "resteuctions", " huans ", "favour ", "adviisng", "govrnment", "representtives", "zize ", " ppol ", "cliamre", "adviisng", "etsablishing",
                     "concluison", "cuationed", " cloisn ", "opoorutnity", "securesustainablefuture", "characteritiscs", "coorinated", "productiviy", "somethig", "stckhold",
                     "exhstiave"," cna ", "monitorng", "increaisng", "scientitss", "claimte", "miniumun","insitutions","thoseee", "metnion", "rpeamble",
                     "knowldge", "anayliss", "decisonming", "mairne ", "obectives", "avaiaebe", "envirnmentla", "agreemnrts", "compoment", "agrements", "avialable", "knowledge",
                     "alredy", "alongisde", "scientificc", "nnegotiating", "commuticies", "iportant", "condut", "rigths", "knwoldge", "deifnitions", "intetntion",
                     "docuemnts", "beacuse", " thses ", "otherwiese", " relly ", "deifinitions", "firts", " rase ", "juridction", "considere", "annunced", "potnetial", "proviing",
                     "assesment", "honour", "preceing", "guiing", "reainess", "accoring", "isxty", "incluisve", "caribbe an", "diveritsy", "itselfwith",
                     "isnce", "ariisng", "finings", "ismultaneously", " thses ", "shoudl", "frameowrks", "midn ym", "tthat", " htere ", "funciotning", " bvest ",
                     "antional", "knowlede", "amnagement", "movilize", "mehcnaism", " us eof ", "activiteis", "rpocess", "operatunalization", "isntrument", "comunities",
                     "kolwdge", "itsrument", "knoledge", "knoeldge", "onbody", "cooperatino", "tehnical", "fashain", "flexibitli", "invilving",
                     " bdies ", "creatng", "prties", "wrking", "woudl", " dela ", "everyhing", "asseginenvirinemtnal", "grdual", " coud ",
                     "prvdinsceintfic", " onw ", "scintific", "tehcnclogy", "addtoinal", "reviewifn", "adviroor", "funotin", "amkgin", "siimilr", "int he", "withother",
                     "duplicatoin", "detiles", "detaield", "exaclt",  "int he", "resevre", "mightnot", " temr ", "descisoinaig", "canot", "clrif", "giid", "spport", "sipport",
                     "prts", "negotition", "negottoin", " iketo ", "establisig", "decisied", "simplif", "workinf", "decied", "dsiturbance", " klum ", "regocnize", "implemntation",
                     "arican", "chapterms", " maing ", "tranpsrency", "gepgraphicap", "implenetation", "basedon", "eleent", "ecperts", "advcive", "wualitifacitos", "2/3 majortiy", "accessss", "acess",
                     "activitybased", "nagoye", "areasidentified", "hsairng", "practuce", "call inmechanismfor", "ccompliance", " clearinghouse ", " mech ", "clearing-ouse", "climat chnage", "coference",
                     "ccompliance committee", "comimitee", " consus ", "coonducted", "complementariy", "adoptingcomplemntary", "cross cutting", "cumulaitve", "deccision", "decison making", "brakets", "brackts",
                     "derivates", "disute", " ebas ", "follow-up", "coastla", "identificatio", "idicative", "implemenation", "implementation & compliance", "incudnig", "arragements", "cooepraiton",
                     "internationalisation", "internationalisato", "involevemnt", "involevment", "activties", "activkites", "activiites", "activkites", "actities", "ofactivities", " agreet ", " hwn ", "debrit",
                     "minium", "glabl", "cooriantion", "monitorin and revie", "activiites", "monitroing", " mrg ", "non-parties", " trits fund", "parameterms",
                     "as far a spracticable", "adjanect", "scinetifc", "knowdge", "knowledged", " statges ", "spaish", " xxx ", "ammend", "cion ", "cn ", "con/flecible", "con/flex", "felible", "felx",
                     "felxble", "felxibel", "felxible", "felxile", "feöxbiien", "flecibel", "flecible", "fleible", "fleixbie", "fleixble", "fleixible", "flex ", "flexibe", "flexibel", "flexibke", "fley",
                     "fleyible", "fllexibke", "flxible", "fpro ", "maby ", "neutrla", "opro ", "resevre", "secnd ", 'complaince', "informationthat", "alreadz", " thge ", " opern ", "thosee", "rewuire", "whcih", "semergency",
                     "abaialbe", "reommend", " deegatio ", "rocess", "letterms", " fro ", "thannk", "societyandwhere", " ave ", "roganisation", " lal ", " fro ", " form ", " ssue ", "assits", " looki ", " qhich ", " fr ",
                     "informationon", "ratinale", " nw ", "importatnt", " ust ", "interpreatiions", " wrk ", "finacialmechanismor", "sessino", "withall", "themselvesto", "submittd", "hsare", "ompilaiton", "tracj", "facilitatiors",
                     "opne", "smallnumbers", "thnk", "pther", "questoinsin", "peple", " tha ", "negotiaiotns", " gove ", " sam ", "submissinos", "haveinng", " nme ", " agai ", " nt he ", "subatante", " latr ", "deends", "strt",
                     "entireyl", " oin ", " thosee, ", "drfting", "paralle", "committeeß", " ony ", "prgram", "awhile", "bissuesd", " takn ", "ont he", "questoins", "negotiing", " hte ", "breifing", " ddi ", "rcieve", " tp ",
                     "coordinat", "oporuntiy", " tates ", "meetin", "aeveryone", "sessoin", "everyton", " wil ", "facilitotors", "reort", " hvae ", "importat", "prwepared", "matterms", "joinging", "issunderstanding", "meetingg",
                     "understading", "pprocess", "beign ", "helpfl", "devlopment", " wihs", "invovle", "metting", "failitators", "interesessional", "prpreciate", "doncisderation", " seonc ", "otehr", "meetinggs", " oehr ",
                     "elegations", " fornt ", "modlities", " understake", "intermssional", "interesessional ", " ahve ", "isntruction", " fourm ", " imilar ", " littel ", " taht ", "rgoups", "repsonse", "quesitons ", "regitsered",
                     "quesiton", "multilateralcontexttts", " oyu ", "disucssionw", "programandthe", "oucomes", " fo ", " arabai ", "quesitons", "outocme", "meetinggs", "incidently", "themsleves", "quesiton", "noimnate", " qith ",
                     "easiers", "quesiton", "delgations", "effeort", "pprocess", "itnerested", "familiared", "definetely", "quesiton", "reposnded", "plattform", "quesiton", "secretaart", "interesessional", "quesiton", "commets", "quesiotns",
                     "epxlore", "negotiatie", " favor ", "ocenas", "plafotm", "joingini", " wihsh ", " goo ", " irst ", "intermsessionaal", "advanatge", " tahnk ", "techincal", "reaosning", " fornt ", "pprocesses", "proceses",
                     "impotant", " beging ", " programm ", " paer ", " wnet ", "therehave", " menat ", "emchanism", "provisiosn", "coferent", "detial", " mroe ", "aprticularly", "coordinatee", "tot ake", " elave ", "breifly",
                     " ans ", " delegationn ", " loor ", "ecologicla", "connecivitx", "problbale", "contexttt", "coordinateing", "ddelegation", "tranaprency", "simplifyy", "turnign", " wach ", "listbut", "estbalihs", "estbasilh",
                     "technoclgy", "relevnt", "tot he", "impoerant", " gruop ", "carricom", "palce", "faciltiaitng", "mehcnaims", "especifieid",
                     " tht ", "rbing", "whetehr", " soem ", "acitviites", "euipemnt", " kee ", "operationaling", "btof", "researhc", "underatdn",
                     "scentiwits", "oblgihations", "coordinateion", "accesss ", "maby ",
					 "capactiy", "ebenefits" , "sstem", "nonmonetar" , "discussinos", "bulateral", "shsll" , "researhc" , "geenral", "dissapointment" , "stagnatio" , "shwoing", "fxx", "flexibleibily",
					 "onyl", "ocena" ,"governane" , "respinsbility", "finsih", "benefti", "somethingn"		 

					 )

badwords.corpus <- str_to_lower(badwords.corpus)

goodwords.corpus <- c("tiered", "traditional knowledge", "people", "CLAM", "science based", "palestine", "options",
                                           "heritage", "parties", "negotiations1", "principle", "integrate", "instrument", "particular",
                                           "countries", "floor", "sharing", "international", "voluntary", "common",
                                           "heritage", "CBD","repetition", "of", "japanese", "heritage",
                                           "behalf", "on behalf of", "on behalf of", "island", "caribbean", "ngo", "secretariat",
                                           "independent international legal advocates", "mauritius","highlight", "psids", "changes",
                                           "environment", "jurisdictional", "states", "broadening", "differentiate", "different", "exploratory",
                                           "activities", "acidification", "transparency", "issues", "biodiversity", "unsustainable", "acidification",
                                           "elements", "climate", "modifying", "algae", "legal", "relevant", "patchwork", "system",
                                           "agreement", "measures", "movements", "notification", "sufficiently", "advancements",
                                           "descriptions", "accoustic", "reference", "planned", "harm", "environment", "treshold", "treshold",
                                           "sovereign", "archipelagic", "continental", "ocean", "transboundary", "account", "adjacent", "impacts",
                                           "instrument", "impact", "mentioned", "basis", "another", "souvereign", 
                                           "wiped", "transboundary", "algeria", "scientific", "section", "evaluate", "where", "available",
                                           "science", "reflect", "ipcc", "consistent", "traditional", "criteria", "ebsa", "sovereign",
                                           "assessment", "definition", "definition", "definition", "cartagena", "DOSI", "itlos",
                                           "cooperation", "abnj", "ioc", "assessment", "assessment", "noaa", "nagoya", "conservation",
                                           "research", "wording", "precautionary", "example", "ioc unesco", "guidelines", "countries", "scratch", "researchers", "technology",
                                           "technology", "technology", "broadly", "involuntary", "appropriate", "extending", "rfmo", "organization", "exising",
                                           "clearing-house", "clearing", "have", "specifies", "instrument", "collect", "information", "following",
                                           "information", "implementation", "desirability", "instrument",  "support", "regret", "authority", "equality", "occurs",
                                           "highest", "recognition", "decision-making", "rfmo", "rfmo", "undermine", "have",
                                           "mechanisms", "measures", "other", "further", "convention", "other",
                                           ' its ', 'have', 'consultation', 'identification', ' I ', 'information', 'assessment', 'assessments', 'by', 'and', 
                                           'committed', 'dumping', 'atlantic', 'comprises', 'mandate', 'memorandum', 'multilateral', 'established', 'arrangement',
                                           'possible', 'located', 'with', 'recommendations', 'conservation', 'secretariat', 'item', 'organisational', 'composition', 'members',
                                           'president', 'following', 'european', 
                                           'what',  'have',  'means',  ' to ',  'respect',  'information',  'sharing',  'task',  'provisions',  'enhance',  'mechanism',  ' is ', 
                                           'countries',  'agreements',  'community',  'regulating',  'appropriate',  'current',  'translating',  'make',  'difficult',  'voluntary',
                                           'genetic',  'their',  'having',  'can',  'does',  'not',  'us',  'be an',  ' and ',  'these',  'issues',  'those',  ' in ',  ' in ', 
                                           'information', 'organization', 'ensure', 'what', 'this', 'context', 'available', 'groups', 'peaceful',
                                           'should', 'what', 'enhance',
                                           'assessments','without','hits','views','voluntary benefit','access','support','benefit','entity','jurisdiction',
                                           'exploitation','government','what','this','context','available','reflect','generation','conservation','support','exercise',
                                           'voluntarily','objective','have',' its ','assessment','knowledge','flexible','substance','negotiations',
                                           'decision','base','organisation','have','promote','capacity','cooperational','effective','procedures','desirable','here',
                                           'committee','can','objective','worth','flexible',
                                           'assessment', 'relationship to other', 'general', 'principles', 'mechanism', 'relation to other', 'terms', 'arrangements',
                                           'not', 'list', 'decision', 'cbtmt', 'coordination', 'terms', 'terms',' provision ', 'situ', 'funding',
                                           'traditional and indigenous knowledge', "development", "decisions", " secretariat ", "operationalized", "flexible", "textual", "like",
                                           "consensus", "final", "anything", "together", "transparent", "provisions", "definition", "tried", "facilitation", "holitic",
                                           "sustainable", "concept", "option", "specific", "changes", " ccamlr ", "inhabitants", "distinguish", "definition of", "important",
                                           "include", "suggestion", "conservation", "conservation", " and ", "adopt", "singapore", "thanks", "broader", "including",
                                           "with small", "bridge", "drafting", "competent", "cooperation:", "include", "african", "international", "into", "consultation", 
                                           "consultation", "monitoring", "responsibility", "monitoring", "existing", "responsibilities", "objectives", "objectives",
                                           "possibility", "relevant", "consistency", "proposed", "activities", "must", "consider", "delegates", "bring",
                                           "consult", "members", "research", "existing", "does", "establishing", "cooperation", "mechanism", "another", "interfere", "mandate",
                                           "size", "flexible", "placement", "consider", "science", "available", "including", "scientific", "infinite", "stakeholders", "stakeholders",
                                           "scientific", "ebsas", "discussion", "outlining", "session", "differentiate", "appropriate", " favor ", "existing", "provisional", "possibility",
                                           "mechanism", "transfer", "institutional", " thresholds ", "management", "building", " as a whole ", "analysis", " traditional knowledge ", " access ", " access ",
                                           "clearing-house mechanism", " traditional knowledge", " cbtmt", " world bank",
                                           "establish", "establish", "establish", "establish",
                                           "establishment", "establishment", "establishment", "establishment", "establishment", "establishment", "establishment", "establishment", "establishment", "establishment", "establishment",
                                           "established", "established", "established", "established", "established", "established", "established", "established", "established", "established", "established", "established",
                                           "establishing", "establishing", "establishing", "establishing", "consider", "possible", "president", "biodiversity", "basis",
                                           "discussions", "discussion", " try ", "plastic", "negotiating", "avialable", "available", "indigenous", "scientific", " knowledge ", " similar ", " broad ", "distinction", " locate ", "demands", " genetic ",
                                           "definition", "distinct", "ensure", "paragraphs", "intrinsic", "cultural", "agreement", "existing", "preferences", "negotiations", "negotiation", "useful", "intersessional", "effective",
                                           "member states", "workshops", " favor ", "massive", " many ", "biodiversity", " cannot ", "consultation", "inclusion", " whole ", "framework",
                                           "sufficient", "sanction", "environmental", "impact", "possible", "discussion", "presidents",
                                           "sincere", "collective", "holistically", " people ", " progress ", "russian", " binding ", " fulfill ", " political ", " raised ",
                                           " undermine ", " sixth ", " opposition ", " limited ", " six ", "souvereignty", " connection ", "civil society", " concerns ", " attention ", "negotiating",
                                           "specific", "aggression", "considerations", " step ", " venezuela ", " affairs ", " adressing ", " aggressive ", " assist ", " and commercialisation ",
                                           " anticipated ", " appropriate ", " atmosphere ", " attempt ", " background ", " balances ", " been "," belongs ", " benefit ", 
                                           " biologist ", " borders ", "bureaucratized", "capabilities", " cop ", " with ", " scientific ", "distinguished", "scientific", " paragraph ",
                                           "contextualize", "excursions", "composition", "russian", "paragraphs", "distinguished", "expressions", "focusing", "contexts",
                                           "federated states of micronesia", "importance to", "recently", "context", " you ", " cannot ", " discussion ", " should ", " scientific ", "evidence", "scientific", 
                                           " consideration ", " only ", " communities ", " possible ", " negative ", " impact ", " positive ", " anegtive ", " pictute ", " scientific ", "scientific", "supposed to",
                                           "postponed", "restrictions", " humans ", "favor ", "advisng ", "government", "representatives", "size ", " pool ", "climate", "advisng ", "establishing",
                                           "conclusion", "cautioned", " closing ", "opportunity", "secure sustainable future", "characteristics", "coordinated", "productivity", "something", "stockholm",
                                           "exhaustive", " can ", "monitoring", "increasing", "scientists", "climate", "minimum", "institutions", "those", "mention", "preamble",
                                           "knowledge", "analysis",  "decision making", "marine ", "objectives", "available", "environmental", "agreements", "component", "agreements", "available", "knowledge",
                                           "already", "alongside", "scientific", "negotiating", "communities", "important", "conduct", "rights", "knowledge", "definitions", "intention",
                                           "document", "because", " these ", "otherwise", " really ", "definitions", "first", " raise ", "jurisdiction", "consider", "announced", "potential", "providing",
                                           "assessment", "honor", "preceding", "guiding", "readiness", "according", "sixty", "inclusive", "caribbean", "diversity", "itself with",
                                           "since", "arising", "findings", "simultaneously", " these ", "should", "frameworks", "mind my", "that", " there ", "functioning", " best ",
                                           "national", "knowledge", "management", "mobilize", "mechanism", " use of ", "activities", "process", "operationalisation", "instrument", "communities",
                                           "knowledge", "instrument", "knowledge", "knowledge", "on body", "cooperation", "technical", "fashion", "flexibility", "involving",
                                           " bodies ", "creating", "parties", "working", "would", " deal ", "everything", "assign environmental", "gradual", " could ",
                                           "provide scientific", " own ", "scientific", "technology", "additional", "reviewing", "advisor", "function", "making", "similar", "in the", "with other",
                                           "duplication", "detailed", "detailed", "excatly", "in the", "reserve", "might not", " term ", "decision making", "can not", "clarify", "good", "support", "support",
                                           "parts", "negotiation", "negotiation", " like to ", "establishing", "decided", "simplify", "working", "decide", "disturbance", " clam ", "recognize", "implementation",
                                           "african", "chapters", " making", "transparency", "geographical", "implementation", "based on", "element", "experts", "advice", "qualifications", "2/3 majority", "access", "access",
                                           "activity based", "nagoya", "areas identified", "sharing", "practice", "call-in mechanism for", "compliance", " clearing-house ", " mechanism ", "clearing-house", "climate change", "conference",
                                           "compliance committee", "committee", " consensus ", "conducted", "complementary", "adopting complemntary", "cross-cutting", "cumulative", "decision", "decison-making", "brackets", "brackets",
                                           "derivatives", "dispute", " ebsas ", "follow up", "coastal", "identification", "indicative", "implementation", "implementation and compliance", "including", "arrangements", "cooperaiton",
                                           "internationalization", "internationalization", "involvement", "involvement", "activities", "activities", "activities", "activities", "activities", "of activities", " agreed ", " when ", "debris",
                                           "minimum", "global", "coordination", "monitoring and review", "activities", "monitoring", " mgr ", "non parties", " trust fund", "parameters",
                                           "as far as practicable", "adjacent", "scientific", "knowledge", "knowledge", " stages", "spanish", " xx ", "amend", "con ", "con ", "con/flexible", "con/flexible", "flexible", "flexible",
                                           "flexible", "flexible", "flexible", "flexible", "flexible", "flexible", "flexible", "flexible", "flexible", "flexible", "flexible", "flexible ", "flexible", "flexible", "flexible", "flexible ",
                                           "flexible", "flexible", "flexible", "pro ", "may ", "neutral", "pro ", "reserve", "second ", 'compliance', "information that", "already", " the ", " open ", "those", "review", "which", "emergency",
                                           "available", "recommend", " delegation ", "process", "letters", " for ", "thank", "society and where", " have ", "organisation", " all ", " for ", " from ", " issue ", "assist", " looking ", "which ", " for ",
                                           "information on", "rationale", " now ", "important", " just ", "interpreations", " work ", "finacial mechanism or", "session", "with all", "themselves to", "submitted", "share", "compilaiton", "track", "facilitators",
                                           "open", "small numbers", "think", "other", "questoins in", "people", " that ", "negotiations", " give ", " same ", "submissions", "having", " me ", " again ", " in the ", "substantive", " later ", "depends", "start",
                                           "entirely", " in ", "those", "drafting", "parallel", "committee", " only ", "program", "a while", "be issued", " taken ", "on the", "questions", "negotiating", " the ", "briefing", " did ", "receive", " to ",
                                           "coordinate", "opportunity", " states ", "meeting", "everyone", "session", "everyone", " will ", "facilitators", "report", " have ", "important", "prepared", "matters", "joining", "missunderstanding", "meeting",
                                           "understanding", "process", "being ", "helpful", "development", " wish", "involve", "meeting", "facilitators", "intersessionals", "appreciate", "concideration", " second ", "other", "meetings", " other ",
                                           "delegations", " front ", "modalities", " undertake", "intersessional", "intersessional", " have ", "isntruction", " forum ", " similar ", " little ", " that ", "groups", "response", "questions", "registered",
                                           "question", "multilateral contexts", " oyu ", "disucssion", "programme and the ", "outcomes", " for ", " arabia ", " questions", "outcome", "meetings", "incidentally", "themselves", "questions", "nominate", " qith ",
                                           "easier", "question", "delegations", "effort", "process", "interested", "familiar", "definitely", "question", "responded", "platform", "question", "secretariat", "intersessional", "question", "comments", "questions",
                                           "explore", "negotiate", " favour ", "oceans", "platform", "joining", " wish ", " good ", " first ", "intersessional", "advantage", " thank ", "technical", "reasoning", " front ", "processes", "processes",
                                           "important", " begin ", " program ", " paper ", " went ", "there have", " meant ", "mechanism", "provisions", "coherent", "detail", " more ", "particularly", "coordinate", "to take", " leave ", "briefly",
                                           " and ", " delegation ", " floor ", "ecological", "connectivity", "probably", "context", "coordinating", "delegation", "transparency", "simplify", "turning", " each ", "list but", "establish", "establish",
                                           "technology", "relevant", "to the", "important", " group ", "caricom", "place", "facilitating", "mechanism", "specified",
                      " that ", "bring", "whether", " some ", "activities", "equipment", " keep ", "operationalizing", "both", "research", "understand",
                      "scientists", "obligations", "coordination", "access", "maybe ",
					  					 "capacity" , "benefits", "system", "non monetary", "discussions", "bilateral", "shall", "research", "general", "disappointment", "stagnating", "showing", "fix", "flexibility", 
					 "only", "ocean", "governance", "responsibility", "finish", "benefit", "something"
					 
                     )
                     
                     
                     
                     
                     
                     goodwords.corpus <- str_to_lower(goodwords.corpus)
                     
                     vect.corpus <- goodwords.corpus
                     names(vect.corpus) <- badwords.corpus
                     ### replace bad words with good words
                     #bbnj$actor <- str_replace_all(bbnj$actor, vect.corpus)
                     temp$comment_obs <- str_replace_all(temp$comment_obs, vect.corpus)
                     temp$observation <- str_replace_all(temp$observation, vect.corpus)
                     temp$option_detail <- str_replace_all(temp$option_detail, vect.corpus)
                     temp$issue_detail <- str_replace_all(temp$issue_detail, vect.corpus)
                     temp$issue_scientific <- str_replace_all(temp$issue_scientific, vect.corpus)
                     temp$pro_contra <- str_replace_all(temp$pro_contra, vect.corpus)
                     